// @category: integration
// @reason: uses CompilerService + set-code + syntax primitives
//
// test_issue_367.cpp — Verify Issue #367 acceptance criteria
// ("[macro][provenance] Enhance SyntaxMarker with origin
//  tracking and integration with mutation log").
//
// Background: After #190, SyntaxMarker::MacroIntroduced gives
// basic observability via syntax-marker-counts. But AI agents
// can't trace "this node was generated by macro X during
// expansion Y, then mutated in Z" — the marker is just an
// enum value.
//
// This scope-limited close ships the FOUNDATION:
//   - A parallel `provenance_` column in FlatAST
//     (std::uint32_t per node, default 0 = no provenance).
//   - `set_provenance(id, prov_id)` + `provenance(id)` accessors.
//   - 2 Aura primitives: `(syntax:set-provenance ...)` and
//     `(syntax:get-provenance ...)` for the workspace.
//
// The actual side-table that maps prov_id →
// {macro_def_id, expansion_id, mutation_id} lives on the host
// (no fixed format — depends on the user's auditability needs).
// AI agents can populate the side-table via the new primitives.
//
// Deferred (separate issues):
//   - Auto-stamp provenance from clone_macro_body (would
//     require threading a thread_local expansion_id through
//     the recursive clone path).
//   - Wire into mutation_log_ so MutationRecord + provenance
//     are correlated (requires MutationRecord to carry an
//     optional prov_id field).
//   - query:macro-origin primitive that walks the side-table.
//
// Test strategy: 3 layers
//   Layer 1: default provenance = 0
//   Layer 2: set + get round-trip (set 42, get returns 42)
//   Layer 3: end-to-end marker + provenance coexist on same node

#include "test_harness.hpp"

import std;
using aura::test::g_failed;
using aura::test::g_passed;

import aura.compiler.service;
import aura.compiler.evaluator;
import aura.compiler.value;
import aura.core.ast;
import aura.core.type;

namespace aura_issue_367_detail {

// ═══════════════════════════════════════════════════════════
// Layer 1: default provenance
// ═══════════════════════════════════════════════════════════

bool test_default_provenance_is_zero() {
    std::println("\n--- AC1: default provenance = 0 (no provenance recorded) ---");
    aura::compiler::CompilerService cs;
    cs.eval("(set-code \"(define x 1)\")");
    auto r = cs.eval("(car (query:find \"x\"))");
    if (!r)
        return false;
    int64_t nid = aura::compiler::types::as_int(*r);

    auto p = cs.eval("(syntax:get-provenance " + std::to_string(nid) + ")");
    if (!p)
        return false;
    int64_t prov = aura::compiler::types::as_int(*p);
    CHECK(prov == 0, "fresh node has default provenance = 0");
    return true;
}

// ═══════════════════════════════════════════════════════════
// Layer 2: set + get round-trip
// ═══════════════════════════════════════════════════════════

bool test_set_get_provenance_round_trip() {
    std::println("\n--- AC2: (syntax:set-provenance ...)(get-provenance ...) round-trip ---");
    aura::compiler::CompilerService cs;
    cs.eval("(set-code \"(define y 0)\")");
    auto r = cs.eval("(car (query:find \"y\"))");
    if (!r)
        return false;
    int64_t nid = aura::compiler::types::as_int(*r);

    // Set provenance to 42 (a host-assigned prov id; the host's
    // side-table maps 42 → {macro_def_id: 7, expansion_id: 99,
    // mutation_id: 13} or whatever the AI agent's audit needs).
    auto set_r = cs.eval("(syntax:set-provenance " + std::to_string(nid) + " 42)");
    if (!set_r)
        return false;
    bool set_ok = aura::compiler::types::as_bool(*set_r);
    CHECK(set_ok, "syntax:set-provenance returns true on success");

    auto get_r = cs.eval("(syntax:get-provenance " + std::to_string(nid) + ")");
    if (!get_r)
        return false;
    int64_t prov = aura::compiler::types::as_int(*get_r);
    CHECK(prov == 42, "syntax:get-provenance returns the set value (42)");

    // Reset to 0.
    cs.eval("(syntax:set-provenance " + std::to_string(nid) + " 0)");
    auto get_r2 = cs.eval("(syntax:get-provenance " + std::to_string(nid) + ")");
    if (!get_r2)
        return false;
    int64_t prov2 = aura::compiler::types::as_int(*get_r2);
    CHECK(prov2 == 0, "syntax:set-provenance 0 clears the provenance");
    return true;
}

// ═══════════════════════════════════════════════════════════
// Layer 3: marker + provenance coexist
// ═══════════════════════════════════════════════════════════

bool test_marker_and_provenance_coexist() {
    std::println("\n--- AC3: syntax-marker + syntax:get-provenance coexist on same node ---");
    aura::compiler::CompilerService cs;
    cs.eval("(set-code \"(define z 99)\")");
    auto r = cs.eval("(car (query:find \"z\"))");
    if (!r)
        return false;
    int64_t nid = aura::compiler::types::as_int(*r);

    // Set marker = MacroIntroduced (1).
    cs.eval("(syntax:set-marker " + std::to_string(nid) + " 1)");
    // Set provenance = 1234.
    cs.eval("(syntax:set-provenance " + std::to_string(nid) + " 1234)");

    auto m = cs.eval("(syntax-marker " + std::to_string(nid) + ")");
    auto p = cs.eval("(syntax:get-provenance " + std::to_string(nid) + ")");
    if (!m || !p)
        return false;
    CHECK(aura::compiler::types::as_int(*m) == 1, "marker = MacroIntroduced (1) preserved");
    CHECK(aura::compiler::types::as_int(*p) == 1234,
          "provenance = 1234 preserved (independent column)");

    // Setting marker doesn't affect provenance.
    cs.eval("(syntax:set-marker " + std::to_string(nid) + " 0)");
    auto p2 = cs.eval("(syntax:get-provenance " + std::to_string(nid) + ")");
    if (!p2)
        return false;
    CHECK(aura::compiler::types::as_int(*p2) == 1234,
          "changing marker doesn't affect provenance column");
    return true;
}

// ═══════════════════════════════════════════════════════════
// Main test runner
// ═══════════════════════════════════════════════════════════

int run_tests() {
    std::println("═══ Issue #367 verification tests ═══\n");

    std::println("Layer 1: default provenance = 0");
    test_default_provenance_is_zero();

    std::println("\nLayer 2: set + get round-trip");
    test_set_get_provenance_round_trip();

    std::println("\nLayer 3: marker + provenance coexist");
    test_marker_and_provenance_coexist();

    std::println("\n════════════════════════════════════════");
    return RUN_ALL_TESTS();
}
} // namespace aura_issue_367_detail

int aura_issue_367_run() {
    return aura_issue_367_detail::run_tests();
}