# CMake generated Testfile for 
# Source directory: /home/dev/code/aura
# Build directory: /home/dev/code/aura/build_rel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[step09_int_42]=] "sh" "-c" "test \"\$(printf '42' | ./aura)\" = 42")
set_tests_properties([=[step09_int_42]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;82;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step09_int_neg5]=] "sh" "-c" "test \"\$(printf '(- 5 10)' | ./aura)\" = -5")
set_tests_properties([=[step09_int_neg5]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;83;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step10_var_error]=] "sh" "-c" "echo x | ./aura 2>&1 | grep -F 'unbound variable'")
set_tests_properties([=[step10_var_error]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;84;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step10_let]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) x)' | ./aura)\" = 10")
set_tests_properties([=[step10_let]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;87;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step10_let_nested]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) (let ((x 20)) x))' | ./aura)\" = 20")
set_tests_properties([=[step10_let_nested]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;88;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_add]=] "sh" "-c" "test \"\$(printf '(+ 1 2)' | ./aura)\" = 3")
set_tests_properties([=[step11_add]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;89;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_sub]=] "sh" "-c" "test \"\$(printf '(- 5 3)' | ./aura)\" = 2")
set_tests_properties([=[step11_sub]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;90;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_mul]=] "sh" "-c" "test \"\$(printf '(* 2 3)' | ./aura)\" = 6")
set_tests_properties([=[step11_mul]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;91;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_nested]=] "sh" "-c" "test \"\$(printf '(+ 1 (* 2 3))' | ./aura)\" = 7")
set_tests_properties([=[step11_nested]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;92;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step12_if_true]=] "sh" "-c" "test \"\$(printf '(if 1 42 0)' | ./aura)\" = 42")
set_tests_properties([=[step12_if_true]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;93;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step12_if_false]=] "sh" "-c" "test \"\$(printf '(if 0 0 99)' | ./aura)\" = 99")
set_tests_properties([=[step12_if_false]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;94;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step15_letrec_fact5]=] "sh" "-c" "test \"\$(printf '(letrec ((fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))) (fact 5))' | ./aura)\" = 120")
set_tests_properties([=[step15_letrec_fact5]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;95;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step15_letrec_fact10]=] "sh" "-c" "test \"\$(printf '(letrec ((fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))) (fact 10))' | ./aura)\" = 3628800")
set_tests_properties([=[step15_letrec_fact10]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;78;add_test;/home/dev/code/aura/CMakeLists.txt;97;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_basic]=] "./test_ir")
set_tests_properties([=[ir_basic]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;148;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_int_42]=] "sh" "-c" "test \"\$(printf '42' | ./aura --ir)\" = 42")
set_tests_properties([=[ir_int_42]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;157;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_add_1_2]=] "sh" "-c" "test \"\$(printf '(+ 1 2)' | ./aura --ir)\" = 3")
set_tests_properties([=[ir_add_1_2]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;158;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_mul_2_3]=] "sh" "-c" "test \"\$(printf '(* 2 3)' | ./aura --ir)\" = 6")
set_tests_properties([=[ir_mul_2_3]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;159;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_if_true]=] "sh" "-c" "test \"\$(printf '(if 1 42 0)' | ./aura --ir)\" = 42")
set_tests_properties([=[ir_if_true]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;160;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_if_false]=] "sh" "-c" "test \"\$(printf '(if 0 0 99)' | ./aura --ir)\" = 99")
set_tests_properties([=[ir_if_false]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;161;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_let_x]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) x)' | ./aura --ir)\" = 10")
set_tests_properties([=[ir_let_x]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;162;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_lambda_call]=] "sh" "-c" "test \"\$(printf '((lambda (x) (* x 2)) 5)' | ./aura --ir)\" = 10")
set_tests_properties([=[ir_lambda_call]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;163;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_lambda_closure]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) ((lambda (y) (+ x y)) 5))' | ./aura --ir)\" = 15")
set_tests_properties([=[ir_lambda_closure]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;153;add_test;/home/dev/code/aura/CMakeLists.txt;164;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_query_call]=] "sh" "-c" "printf '(+ 1 2)' | ./aura --query '(node-type Call)' | grep -q '1 matches'")
set_tests_properties([=[cli_query_call]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;168;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_query_callee]=] "sh" "-c" "printf '(+ 1 2)' | ./aura --query '(callee \"+\")' | grep -q '1 matches'")
set_tests_properties([=[cli_query_callee]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;173;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_query_and_fix]=] "sh" "-c" "printf '(+ 1 2)' | ./aura --query-and-fix '(node-type LiteralInt)' '(LiteralInt 99)' | grep -q 'applied=true'")
set_tests_properties([=[cli_query_and_fix]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;178;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_auto_fix]=] "sh" "-c" "printf '(+ 1 2)' | timeout 10 ./aura --auto-fix | grep -q 'auto-fix'")
set_tests_properties([=[cli_auto_fix]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;183;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_serve_error]=] "sh" "-c" "printf '(+ x 1)' | timeout 5 ./aura --serve | grep -q -F 'kind'")
set_tests_properties([=[cli_serve_error]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;188;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_serve_ok]=] "sh" "-c" "printf '(+ 1 2)' | timeout 5 ./aura --serve | grep -q -F 'ok'")
set_tests_properties([=[cli_serve_ok]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;191;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[tc_int]=] "sh" "-c" "printf '42' | timeout 5 ./aura --typecheck | grep -q 'type: Int'")
set_tests_properties([=[tc_int]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;194;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[tc_lambda]=] "sh" "-c" "printf '(lambda (x) x)' | timeout 5 ./aura --typecheck | grep -q -e '->'")
set_tests_properties([=[tc_lambda]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;197;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[tc_let]=] "sh" "-c" "printf '(let ((x 10)) x)' | timeout 5 ./aura --typecheck | grep -q 'type: Int'")
set_tests_properties([=[tc_let]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;200;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[inspect_closure_fact]=] "sh" "-c" "printf '(letrec ((fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))) (fact 5))' | timeout 5 ./aura --inspect | grep -q 'closures (1)'")
set_tests_properties([=[inspect_closure_fact]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;205;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[inspect_no_closure]=] "sh" "-c" "printf '(+ 1 2)' | timeout 5 ./aura --inspect | grep -q 'closures (0)'")
set_tests_properties([=[inspect_no_closure]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;209;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[inspect_env]=] "sh" "-c" "printf '(let ((x 10)) x)' | timeout 5 ./aura --env | grep -q 'result: 10'")
set_tests_properties([=[inspect_env]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;213;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[validate_node_layout]=] "./validate-node-layout")
set_tests_properties([=[validate_node_layout]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;223;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cache_write]=] "sh" "-c" "printf '(+ 1 2)' | timeout 5 ./aura --cache /tmp/test_aura.cache 2>&1 | grep -q 'cache written'")
set_tests_properties([=[cache_write]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;228;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[reflect_ir_instruction]=] "./aura-reflect" "--ir-instruction")
set_tests_properties([=[reflect_ir_instruction]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;239;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[reflect_schema]=] "./aura-reflect" "--schema")
set_tests_properties([=[reflect_schema]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;242;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[schema_ir_instruction]=] "./aura-schema")
set_tests_properties([=[schema_ir_instruction]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;252;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[schema_serve]=] "sh" "-c" "./aura-schema --serve | head -1 | grep -q schema")
set_tests_properties([=[schema_serve]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;255;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[macro_twice]=] "sh" "-c" "printf '(begin (defmacro (twice x) (+ x x)) (twice 5))' | timeout 5 ./aura | grep -q '10'")
set_tests_properties([=[macro_twice]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;260;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[macro_free_var]=] "sh" "-c" "printf '(begin (define base 10) (defmacro (add-base x) (+ x base)) (add-base 5))' | timeout 5 ./aura | grep -q '15'")
set_tests_properties([=[macro_free_var]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;263;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[macro_unused_param_warning]=] "sh" "-c" "printf '(defmacro (const x) 42)' | timeout 5 ./aura 2>&1 | grep -q 'never used'")
set_tests_properties([=[macro_unused_param_warning]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;266;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[macro_constant_body_warning]=] "sh" "-c" "printf '(defmacro (always) 42)' | timeout 5 ./aura 2>&1 | grep -q 'does not reference'")
set_tests_properties([=[macro_constant_body_warning]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;269;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[type_of_int]=] "sh" "-c" "printf '(display (type-of 42))' | timeout 5 ./aura 2>&1 | grep -q 'Int'")
set_tests_properties([=[type_of_int]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;274;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[type_of_pair]=] "sh" "-c" "printf '(display (type-of (cons 1 2)))' | timeout 5 ./aura 2>&1 | grep -q 'Pair'")
set_tests_properties([=[type_of_pair]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;277;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[type_of_bool]=] "sh" "-c" "printf '(display (type-of (if 1 0 1)))' | timeout 5 ./aura 2>&1 | grep -q 'Bool'")
set_tests_properties([=[type_of_bool]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;280;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[type_check_true]=] "sh" "-c" "printf '(type? 42 \"Int\")' | timeout 5 ./aura | grep -q '^1\$'")
set_tests_properties([=[type_check_true]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;283;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[type_check_false]=] "sh" "-c" "printf '(type? 42 \"String\")' | timeout 5 ./aura | grep -q '^0\$'")
set_tests_properties([=[type_check_false]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;286;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[float_literal]=] "sh" "-c" "printf '3.14' | timeout 5 ./aura | grep -q '3.14'")
set_tests_properties([=[float_literal]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;291;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[float_arith]=] "sh" "-c" "printf '(+ 3.14 2.86)' | timeout 5 ./aura | grep -q '6'")
set_tests_properties([=[float_arith]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;294;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[float_mixed]=] "sh" "-c" "printf '(+ 5 2.5)' | timeout 5 ./aura | grep -q '7.5'")
set_tests_properties([=[float_mixed]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_rel" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;297;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
