// Aura standalone runtime stub
// Linked with LLVM-compiled .o to produce native binary.
// Provides runtime functions that LLVM JIT code references.
//
// Build: gcc -c runtime.c -o runtime.o
// Link:  gcc program.o runtime.o -o program -lm

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

// ── Pair heap (fixed size for now) ─────────────────────────
#define MAX_PAIRS 1048576
static struct { int64_t car, cdr; } pairs[MAX_PAIRS];
static uint64_t pair_count = 0;

// ── String heap ────────────────────────────────────────────
#define MAX_STRINGS 65536
static char* strings[MAX_STRINGS];
static uint64_t string_count = 0;

// ── Closure table ──────────────────────────────────────────
#define MAX_CLOSURES 4096
typedef int64_t (*ScalarFn)(int64_t*, uint32_t);
static struct { ScalarFn fn; uint32_t local_count; } closures[MAX_CLOSURES];
static uint64_t closure_count = 0;

// ── Cell heap ──────────────────────────────────────────────
#define MAX_CELLS 262144
static int64_t cells[MAX_CELLS];
static uint64_t cell_count = 0;

// ── Runtime functions called from LLVM IR ──────────────────

int64_t aura_display_int(int64_t val) {
    printf("%ld", (long)val);
    fflush(stdout);
    return val;
}

int64_t aura_display_char(int64_t val) {
    putchar((int)val);
    fflush(stdout);
    return val;
}

void aura_newline(void) {
    putchar('\n');
    fflush(stdout);
}

int64_t aura_alloc_closure(int64_t func_id) {
    if (closure_count >= MAX_CLOSURES) {
        fprintf(stderr, "runtime: closure overflow\n");
        exit(1);
    }
    uint64_t id = closure_count++;
    closures[id].fn = NULL;  // Set by register_closure
    closures[id].local_count = 0;
    return (int64_t)id;
}

void aura_closure_capture(int64_t closure_id, int64_t idx, int64_t val) {
    (void)closure_id; (void)idx; (void)val;
}

int64_t aura_closure_call(int64_t closure_id, int64_t* args, int64_t argc) {
    if ((uint64_t)closure_id >= closure_count || !closures[closure_id].fn) {
        fprintf(stderr, "runtime: invalid closure call\n");
        return 0;
    }
    return closures[closure_id].fn(args, (uint32_t)argc);
}

int64_t aura_new_cell(void) {
    if (cell_count >= MAX_CELLS) {
        fprintf(stderr, "runtime: cell overflow\n");
        exit(1);
    }
    return (int64_t)(cell_count++);
}

int64_t aura_cell_get(int64_t cell_id) {
    if ((uint64_t)cell_id >= cell_count) return 0;
    return cells[cell_id];
}

void aura_cell_set(int64_t cell_id, int64_t val) {
    if ((uint64_t)cell_id >= cell_count) return;
    cells[cell_id] = val;
}

int64_t aura_alloc_pair(int64_t car, int64_t cdr) {
    if (pair_count >= MAX_PAIRS) {
        fprintf(stderr, "runtime: pair overflow\n");
        exit(1);
    }
    uint64_t id = pair_count++;
    pairs[id].car = car;
    pairs[id].cdr = cdr;
    return (int64_t)id;
}

int64_t aura_pair_car(int64_t pair_id) {
    if ((uint64_t)pair_id >= pair_count) return 0;
    return pairs[pair_id].car;
}

int64_t aura_pair_cdr(int64_t pair_id) {
    if ((uint64_t)pair_id >= pair_count) return 0;
    return pairs[pair_id].cdr;
}

int64_t aura_prim_call(int64_t prim_id, int64_t arg) {
    (void)prim_id;
    return arg;
}

// ── Main entry point ────────────────────────────────────────
// __top__ is the entry function generated by LLVM compilation.
int64_t __top__(int64_t* args, uint32_t argc);

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    int64_t args[8] = {0};
    int64_t result = __top__(args, 0);
    if (result != 0)
        printf("%ld\n", (long)result);
    return 0;
}
