#!/usr/bin/env python3
"""Generate issue test bundle mains and CMake glue.

Reads tests/fixtures/issue_link_profiles.json and emits:
  - tests/bundles/test_issues_<profile>_main.cpp  (one per bundle profile)
  - cmake/AuraIssueBundles.cmake                  (aura_add_issue_bundle helper)

Usage:
  python3 scripts/gen_issue_bundles.py
  python3 scripts/gen_issue_bundles.py --migrate-sources
  python3 scripts/gen_issue_bundles.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROFILES_JSON = ROOT / "tests" / "fixtures" / "issue_link_profiles.json"
EXTRAS_JSON = ROOT / "tests" / "fixtures" / "issue_bundle_extras.json"
CMAKE_LISTS = ROOT / "CMakeLists.txt"
BUNDLES_DIR = ROOT / "tests" / "bundles"
OUT_CMAKE = ROOT / "cmake" / "AuraIssueBundles.cmake"

# Profiles merged into one executable each (reflect/standalone stay separate).
BUNDLE_PROFILES = (
    "light",
    "jit",
    "jit_minimal",
    "jit_contract",
    "jit_tests",
    "fiber",
)

PROFILE_LINK_HELPER: dict[str, str | None] = {
    "light": None,
    "jit": "aura_issue_test_link_llvm_jit",
    "jit_minimal": "aura_issue_test_link_llvm_jit_minimal",
    "jit_contract": "aura_issue_test_link_llvm_jit_contract",
    "jit_tests": "aura_issue_test_link_llvm_jit_tests",
    "fiber": "aura_issue_test_link_llvm_fiber_stubs",
}

GENERATED_BANNER = "// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit\n"
CMAKE_BANNER = "# AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit\n"

MAIN_RE = re.compile(r"\bint\s+main\s*\(\s*\)")
RUN_FN_RE = re.compile(r"\bint\s+(aura_issue_\w+_run)\s*\(\s*\)")

# CMake parsing helpers
ADD_ISSUE_RE = re.compile(r"^aura_add_issue_test\(([^)]+)\)\s*$")
INCLUDE_RE = re.compile(r"^target_include_directories\((\S+)\s+PRIVATE\s+(.+)\)\s*$")
SOURCES_RE = re.compile(r"^target_sources\((\S+)\s+PRIVATE\s*$")
COMPILE_OPTS_RE = re.compile(r"^target_compile_options\((\S+)\s+PRIVATE\s+(.+)\)\s*$")
SOURCE_FLAGS_RE = re.compile(r"^set_source_files_properties\((\S+)\s+PROPERTIES\s+COMPILE_FLAGS\s+\"([^\"]+)\"\)\s*$")
LINK_HELPER_RE = re.compile(r"^aura_issue_test_link_\w+\((\S+)\)\s*$")
OBSERVABILITY_RE = re.compile(r"^aura_issue_test_observability\((\S+)\)\s*$")


def run_function_name(member: str) -> str:
    """Map a test source stem to its bundle entry-point symbol.

    Convention (short form):
      test_issue_147        -> aura_issue_147_run
      test_issue_159_bench  -> aura_issue_159_bench_run
      test_error_merr       -> aura_issue_error_merr_run
    """
    if member.startswith("test_issue_"):
        stem = member[len("test_issue_") :]
    elif member.startswith("test_"):
        stem = member[len("test_") :]
    else:
        stem = member
    return f"aura_issue_{stem}_run"


def load_profiles() -> dict[str, list[str]]:
    data = json.loads(PROFILES_JSON.read_text(encoding="utf-8"))
    return {k: list(v) for k, v in data.items()}


def load_static_bundle_extras() -> dict[str, dict]:
    if not EXTRAS_JSON.is_file():
        return {}
    raw = json.loads(EXTRAS_JSON.read_text(encoding="utf-8"))
    out: dict[str, dict] = {}
    for profile, data in raw.items():
        out[profile] = {
            "includes": data.get("includes", []),
            "sources": data.get("sources", []),
            "compile_options": data.get("compile_options", []),
            "source_flags": data.get("source_flags", {}),
            "per_source_compile_options": data.get("per_source_compile_options", {}),
            "observability": bool(data.get("observability", profile == "light")),
        }
    return out


def parse_issue_test_extras(cmake_text: str) -> dict[str, dict]:
    """Parse per-target CMake extras following aura_add_issue_test(NAME)."""
    extras: dict[str, dict] = {}
    current: str | None = None
    collecting_sources = False
    source_lines: list[str] = []
    allow_orphan_source_flags = False

    def new_extra(name: str) -> dict:
        return {
            "includes": [],
            "sources": [],
            "compile_options": [],
            "per_source_compile_options": {},
            "source_compile_flags": {},
            "observability": False,
            "link_helper": None,
        }

    def flush_sources() -> None:
        nonlocal collecting_sources, source_lines
        if current and source_lines:
            extras[current]["sources"].extend(source_lines)
        collecting_sources = False
        source_lines = []

    def end_block() -> None:
        nonlocal current, allow_orphan_source_flags
        flush_sources()
        current = None
        allow_orphan_source_flags = False

    block_starters = (
        "aura_add_issue_test(",
        "aura_add_issue_test_reflect_standalone(",
        "aura_add_issue_test_standalone(",
        "add_executable(",
        "add_library(",
        "add_custom_target(",
    )

    for raw in cmake_text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if any(line.startswith(prefix) for prefix in block_starters):
            if ADD_ISSUE_RE.match(line):
                flush_sources()
                current = ADD_ISSUE_RE.match(line).group(1).strip()
                extras.setdefault(current, new_extra(current))
                allow_orphan_source_flags = False
            else:
                end_block()
            continue

        if current is None:
            continue

        if collecting_sources:
            if line == ")":
                flush_sources()
                continue
            source_lines.append(line)
            continue

        m = SOURCES_RE.match(line)
        if m and m.group(1) == current:
            collecting_sources = True
            continue

        m = INCLUDE_RE.match(line)
        if m and m.group(1) == current:
            extras[current]["includes"].extend(m.group(2).split())
            continue

        m = COMPILE_OPTS_RE.match(line)
        if m and m.group(1) == current:
            opt = m.group(2)
            # Whole-target flags are kept; per-file flags are routed below.
            if opt == "-freflection":
                extras[current]["per_source_compile_options"][f"tests/{current}.cpp"] = opt
            else:
                extras[current]["compile_options"].append(opt)
            continue

        m = SOURCE_FLAGS_RE.match(line)
        if m and allow_orphan_source_flags:
            extras[current]["source_compile_flags"][m.group(1)] = m.group(2)
            continue

        if OBSERVABILITY_RE.match(line) and line.endswith(f"({current})"):
            extras[current]["observability"] = True
            continue

        m = LINK_HELPER_RE.match(line)
        if m and m.group(1) == current:
            extras[current]["link_helper"] = line.split("(")[0]
            allow_orphan_source_flags = True
            continue

        # Any other command ends the aura_add_issue_test block.
        if not line.startswith("add_test("):
            end_block()

    flush_sources()
    return extras


def union_bundle_extras(members: list[str], all_extras: dict[str, dict]) -> dict:
    includes: set[str] = set()
    sources: set[str] = set()
    compile_options: set[str] = set()
    source_flags: dict[str, str] = {}
    needs_observability = False

    for member in members:
        ex = all_extras.get(member, {})
        includes.update(ex.get("includes", []))
        sources.update(ex.get("sources", []))
        compile_options.update(ex.get("compile_options", []))
        if ex.get("observability"):
            needs_observability = True
        for src, flags in ex.get("source_compile_flags", {}).items():
            source_flags[src] = flags

    per_source_compile_options: dict[str, str] = {}
    for member in members:
        ex = all_extras.get(member, {})
        per_source_compile_options.update(ex.get("per_source_compile_options", {}))

    return {
        "includes": sorted(includes),
        "sources": sorted(sources),
        "compile_options": sorted(compile_options),
        "source_flags": source_flags,
        "per_source_compile_options": per_source_compile_options,
        "observability": needs_observability,
    }


def render_bundle_main(profile: str, members: list[str]) -> str:
    lines = [
        GENERATED_BANNER.rstrip(),
        f"// Bundle driver for profile: {profile}",
        "",
        "#include <cstdio>",
        "",
        '#include "test_harness.hpp"',
        "",
    ]

    for member in members:
        fn = run_function_name(member)
        lines.append(f"extern int {fn}();")

    lines.extend(
        [
            "",
            "int main() {",
            "    struct Member {",
            "        const char* name;",
            "        int (*run)();",
            "    };",
            "    Member members[] = {",
        ]
    )

    for member in members:
        fn = run_function_name(member)
        lines.append(f'        {{"{member}", {fn}}},')

    lines.extend(
        [
            "    };",
            "",
            "    int passed = 0;",
            "    int failed = 0;",
            "    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));",
            "",
            "    for (int i = 0; i < n_members; ++i) {",
            '        std::fprintf(stdout, "\\n════ Bundle member: %s ════\\n", members[i].name);',
            "        const int rc = members[i].run();",
            "        if (rc == 0) {",
            "            ++passed;",
            "        } else {",
            "            ++failed;",
            "        }",
            "    }",
            "",
            '    std::fprintf(stdout, "──────────────────────────────────────\\n");',
            '    std::fprintf(stdout, "Total: %d passed, %d failed\\n", passed, failed);',
            "    return failed > 0 ? 1 : 0;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_cmake(profiles: dict[str, list[str]], all_extras: dict[str, dict]) -> str:
    chunks = [
        CMAKE_BANNER.rstrip(),
        "# Issue test bundles: one executable per link profile.",
        "# Include from CMakeLists.txt after cmake/AuraTest.cmake.",
        "",
        "function(aura_add_issue_bundle PROFILE)",
        '    string(TOUPPER "${PROFILE}" _profile_uc)',
        '    set(_members_var "AURA_ISSUE_BUNDLE_${_profile_uc}_MEMBERS")',
        "    if(NOT DEFINED ${_members_var})",
        '        message(FATAL_ERROR "Unknown issue bundle profile: ${PROFILE}")',
        "    endif()",
        '    set(_target "test_issues_${PROFILE}")',
        "    set(_members ${${_members_var}})",
        "",
        '    set(_sources "tests/bundles/test_issues_${PROFILE}_main.cpp")',
        "    foreach(_m IN LISTS _members)",
        '        list(APPEND _sources "tests/${_m}.cpp")',
        "    endforeach()",
        "",
        "    add_executable(${_target} ${_sources})",
        "    set_property(TARGET ${_target} PROPERTY CXX_MODULE_STD ON)",
        "    target_include_directories(${_target} PRIVATE src tests)",
        "    aura_test_compile_options(${_target})",
        "    target_link_libraries(${_target} PRIVATE aura_test_objects pthread stdc++ stdc++exp aura-reflect)",
        "",
        "    # Per-target define (not per-source) so the same test .cpp can",
        "    # also be built as a standalone aura_add_issue_test binary.",
        "    target_compile_definitions(${_target} PRIVATE AURA_ISSUE_BUNDLE_MEMBER=1)",
        "",
        '    if(PROFILE STREQUAL "light")',
        "        aura_issue_test_observability(${_target})",
        '    elseif(PROFILE STREQUAL "jit")',
        "        aura_issue_test_link_llvm_jit(${_target})",
        '    elseif(PROFILE STREQUAL "jit_minimal")',
        "        aura_issue_test_link_llvm_jit_minimal(${_target})",
        '    elseif(PROFILE STREQUAL "jit_contract")',
        "        aura_issue_test_link_llvm_jit_contract(${_target})",
        '    elseif(PROFILE STREQUAL "jit_tests")',
        "        aura_issue_test_link_llvm_jit_tests(${_target})",
        '    elseif(PROFILE STREQUAL "fiber")',
        "        aura_issue_test_link_llvm_fiber_stubs(${_target})",
        "    else()",
        '        message(FATAL_ERROR "aura_add_issue_bundle: unsupported profile ${PROFILE}")',
        "    endif()",
        "",
        "    _aura_issue_bundle_apply_extras(${_target} ${PROFILE})",
        "",
        "    add_test(NAME ${_target}_verification COMMAND ./${_target})",
        "endfunction()",
        "",
        "function(_aura_issue_bundle_apply_extras TARGET PROFILE)",
        '    if(PROFILE STREQUAL "light")',
    ]

    static_extras = load_static_bundle_extras()
    parsed_extras = parse_issue_test_extras(CMAKE_LISTS.read_text(encoding="utf-8")) if CMAKE_LISTS.is_file() else {}

    def profile_extras(profile: str) -> dict:
        base = static_extras.get(profile, {})
        merged = union_bundle_extras(profiles.get(profile, []), parsed_extras)
        return {
            "includes": sorted(set(base.get("includes", [])) | set(merged["includes"])),
            "sources": sorted(set(base.get("sources", [])) | set(merged["sources"])),
            "compile_options": sorted(set(base.get("compile_options", [])) | set(merged["compile_options"])),
            "source_flags": {**merged["source_flags"], **base.get("source_flags", {})},
            "per_source_compile_options": {
                **merged.get("per_source_compile_options", {}),
                **base.get("per_source_compile_options", {}),
            },
            "observability": base.get("observability", False) or merged["observability"],
        }

    light_extras = profile_extras("light")
    chunks.extend(_render_profile_extras_body("light", light_extras, indent=8))

    for profile in BUNDLE_PROFILES:
        if profile == "light":
            continue
        extras = profile_extras(profile)
        if not any(
            [
                extras["includes"],
                extras["sources"],
                extras["compile_options"],
                extras["source_flags"],
                extras["observability"],
            ]
        ):
            continue
        pad = " " * 4
        chunks.append(f'{pad}elseif(PROFILE STREQUAL "{profile}")')
        chunks.extend(_render_profile_extras_body(profile, extras, indent=8))

    chunks.extend(
        [
            "    endif()",
            "endfunction()",
            "",
        ]
    )

    for profile in BUNDLE_PROFILES:
        members = profiles.get(profile, [])
        cmake_list = ";".join(members)
        uc = profile.upper()
        chunks.append(f"set(AURA_ISSUE_BUNDLE_{uc}_MEMBERS {cmake_list})")

    chunks.append("")

    return "\n".join(chunks)


def _render_profile_extras_body(profile: str, extras: dict, indent: int) -> list[str]:
    pad = " " * indent
    lines: list[str] = []

    for inc in extras["includes"]:
        # src is already applied globally; only emit extra roots.
        filtered = [p for p in inc.split() if p != "src"]
        if not filtered:
            continue
        args = " ".join(filtered)
        lines.append(f"{pad}target_include_directories(${{TARGET}} PRIVATE {args})")

    for src in extras["sources"]:
        lines.append(f"{pad}target_sources(${{TARGET}} PRIVATE {src})")

    for opt in extras["compile_options"]:
        lines.append(f"{pad}target_compile_options(${{TARGET}} PRIVATE {opt})")

    for src, opt in sorted(extras.get("per_source_compile_options", {}).items()):
        lines.append(f'{pad}set_source_files_properties({src} PROPERTIES COMPILE_OPTIONS "{opt}")')

    for src, flags in sorted(extras["source_flags"].items()):
        lines.append(f'{pad}set_source_files_properties({src} PROPERTIES COMPILE_FLAGS "{flags}")')

    if extras["observability"] and profile != "light":
        lines.append(f"{pad}aura_issue_test_observability(${{TARGET}})")

    return lines


def generate_outputs() -> tuple[dict[str, str], str]:
    profiles = load_profiles()
    all_extras = load_static_bundle_extras()
    if CMAKE_LISTS.is_file():
        parsed = parse_issue_test_extras(CMAKE_LISTS.read_text(encoding="utf-8"))
        for profile in BUNDLE_PROFILES:
            merged = union_bundle_extras(profiles.get(profile, []), parsed)
            if any(
                [
                    merged["includes"],
                    merged["sources"],
                    merged["compile_options"],
                    merged["source_flags"],
                    merged["observability"],
                ]
            ):
                all_extras[profile] = merged

    mains: dict[str, str] = {}
    for profile in BUNDLE_PROFILES:
        members = profiles.get(profile, [])
        if not members:
            raise SystemExit(f"profile {profile!r} has no members in {PROFILES_JSON}")
        mains[profile] = render_bundle_main(profile, members)

    cmake = render_cmake(profiles, all_extras)
    return mains, cmake


def write_outputs(mains: dict[str, str], cmake: str) -> None:
    BUNDLES_DIR.mkdir(parents=True, exist_ok=True)
    for profile, content in mains.items():
        path = BUNDLES_DIR / f"test_issues_{profile}_main.cpp"
        path.write_text(content, encoding="utf-8")
    OUT_CMAKE.write_text(cmake, encoding="utf-8")


def check_outputs(mains: dict[str, str], cmake: str) -> list[str]:
    errors: list[str] = []
    for profile, expected in mains.items():
        path = BUNDLES_DIR / f"test_issues_{profile}_main.cpp"
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            errors.append(f"stale {path.relative_to(ROOT)}")
    if not OUT_CMAKE.exists():
        errors.append(f"missing {OUT_CMAKE.relative_to(ROOT)}")
    elif OUT_CMAKE.read_text(encoding="utf-8") != cmake:
        errors.append(f"stale {OUT_CMAKE.relative_to(ROOT)}")
    return errors


def _detail_namespace(member: str) -> str:
    if member.startswith("test_issue_"):
        stem = member[len("test_issue_") :]
    elif member.startswith("test_"):
        stem = member[len("test_") :]
    else:
        stem = member
    return f"aura_issue_{stem}_detail"


def _unwrap_broken_bundle_wrap(text: str) -> str:
    """Undo prior anonymous-namespace wrap that left run() outside."""
    text = re.sub(
        r"\nnamespace \{\n// aura bundle TU isolation\n",
        "\n",
        text,
        count=1,
    )
    text = re.sub(r"\n\}  // anonymous namespace \(bundle TU\)\n\n", "\n", text, count=1)
    return text


def wrap_member_in_detail_namespace(path: Path, member: str) -> bool:
    """Isolate bundle member symbols in a per-file named namespace."""
    text = _unwrap_broken_bundle_wrap(path.read_text(encoding="utf-8"))
    detail_ns = _detail_namespace(member)
    fn = run_function_name(member)
    if f"namespace {detail_ns}" in text and f"int {fn}() {{ return {detail_ns}::run_tests(); }}" in text:
        return False
    run_pat = re.compile(rf"\bint\s+{re.escape(fn)}\s*\(\s*\)")
    run_m = run_pat.search(text)
    if not run_m:
        return False

    head = text[: run_m.start()]
    run_body = text[run_m.end() :]
    run_open = re.match(r"\s*\{", run_body)
    if not run_open:
        return False
    run_body = run_body[run_open.start() :]

    # Split run function body from remainder (usually empty).
    brace = 0
    run_end = 0
    started = False
    for i, ch in enumerate(run_body):
        if ch == "{":
            brace += 1
            started = True
        elif ch == "}":
            brace -= 1
            if started and brace == 0:
                run_end = i + 1
                break
    run_fn_text = run_body[:run_end]  # includes outer { ... }
    remainder = run_body[run_end:]

    lines = head.splitlines(keepends=True)
    insert_at = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            if insert_at == i:
                insert_at = i + 1
            continue
        if (
            stripped.startswith("#include")
            or stripped.startswith("import ")
            or stripped.startswith("using aura::test::")
            or stripped.startswith("// @category:")
            or stripped.startswith("// @reason:")
        ):
            insert_at = i + 1
            continue
        if stripped.startswith("//") and insert_at == i:
            insert_at = i + 1
            continue
        break

    wrapped = (
        "".join(lines[:insert_at])
        + f"namespace {detail_ns} {{\n"
        + "".join(lines[insert_at:])
        + f"int run_tests(){run_fn_text}\n"
        + f"}}  // namespace {detail_ns}\n\n"
        + f"int {fn}() {{ return {detail_ns}::run_tests(); }}\n"
        + remainder
    )
    if wrapped == path.read_text(encoding="utf-8"):
        return False
    path.write_text(wrapped, encoding="utf-8")
    return True


def wrap_bundle_members(profiles: dict[str, list[str]], dry_run: bool) -> list[str]:
    changed: list[str] = []
    members = sorted({m for p in BUNDLE_PROFILES for m in profiles.get(p, [])})
    for member in members:
        path = ROOT / "tests" / f"{member}.cpp"
        if not path.exists():
            continue
        if dry_run:
            text = path.read_text(encoding="utf-8")
            detail_ns = _detail_namespace(member)
            fn = run_function_name(member)
            ok = f"namespace {detail_ns}" in text and f"int {fn}() {{ return {detail_ns}::run_tests(); }}" in text
            if not ok:
                changed.append(str(path.relative_to(ROOT)))
            continue
        if wrap_member_in_detail_namespace(path, member):
            changed.append(str(path.relative_to(ROOT)))
    return changed


def migrate_member_sources(profiles: dict[str, list[str]], dry_run: bool) -> list[str]:
    """Rename int main() -> int aura_issue_<stem>_run() in bundle member TUs."""
    changed: list[str] = []
    members = sorted({m for p in BUNDLE_PROFILES for m in profiles.get(p, [])})

    for member in members:
        path = ROOT / "tests" / f"{member}.cpp"
        if not path.exists():
            print(f"warning: missing source for bundle member {member}", file=sys.stderr)
            continue

        text = path.read_text(encoding="utf-8")
        fn = run_function_name(member)

        if RUN_FN_RE.search(text):
            continue
        if not MAIN_RE.search(text):
            print(f"warning: no int main() in {path.relative_to(ROOT)}", file=sys.stderr)
            continue

        new_text = MAIN_RE.sub(f"int {fn}()", text, count=1)
        if new_text == text:
            continue

        changed.append(str(path.relative_to(ROOT)))
        if not dry_run:
            path.write_text(new_text, encoding="utf-8")

    return changed


BLOCK_START_RE = re.compile(r"^aura_add_issue_test(?:_reflect_standalone|_standalone)?\(([^)]+)\)\s*$")
BLOCK_STOP_RE = re.compile(
    r"^(aura_add_issue_test|aura_add_issue_test_reflect_standalone|"
    r"aura_add_issue_test_standalone|add_executable\(|add_custom_target\()"
)


def bundled_members(profiles: dict[str, list[str]]) -> set[str]:
    return {m for p in BUNDLE_PROFILES for m in profiles.get(p, [])}


def non_bundled_issue_targets(cmake_text: str, bundled: set[str]) -> list[str]:
    """Targets that stay as individual executables after bundling."""
    keep: list[str] = []
    for line in cmake_text.splitlines():
        m = BLOCK_START_RE.match(line.strip())
        if m:
            name = m.group(1)
            if name not in bundled:
                keep.append(name)
        if line.strip().startswith("add_executable(test_issue_"):
            name = line.strip().split("(")[1].split()[0]
            if name not in bundled:
                keep.append(name)
    return sorted(set(keep))


def prune_cmake_lists(profiles: dict[str, list[str]]) -> str:
    """Remove per-member aura_add_issue_test blocks; wire bundles + aggregate."""
    bundled = bundled_members(profiles)
    text = CMAKE_LISTS.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)

    out: list[str] = []
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        m = re.match(r"^aura_add_issue_test\(([^)]+)\)\s*$", stripped)
        if m and m.group(1) in bundled:
            i += 1
            while i < len(lines) and not BLOCK_STOP_RE.match(lines[i].strip()):
                i += 1
            continue
        out.append(lines[i])
        i += 1

    merged = "".join(out)
    if "include(${CMAKE_SOURCE_DIR}/cmake/AuraIssueBundles.cmake)" not in merged:
        merged = merged.replace(
            "include(${CMAKE_SOURCE_DIR}/cmake/AuraTest.cmake)\n",
            "include(${CMAKE_SOURCE_DIR}/cmake/AuraTest.cmake)\n"
            "include(${CMAKE_SOURCE_DIR}/cmake/AuraIssueBundles.cmake)\n",
        )

    keep = non_bundled_issue_targets(text, bundled)
    bundle_targets = [f"test_issues_{p}" for p in BUNDLE_PROFILES]
    invoke_lines = [
        "\n# Issue test bundles — one link per profile (see scripts/gen_issue_bundles.py)\n",
    ]
    for p in BUNDLE_PROFILES:
        invoke_lines.append(f"aura_add_issue_bundle({p})\n")

    agg_lines = [
        "\nadd_custom_target(all_test_issue_targets ALL)\n",
    ]
    for t in bundle_targets + keep:
        agg_lines.append(f"add_dependencies(all_test_issue_targets {t})\n")

    agg_start = merged.find("add_custom_target(all_test_issue_targets ALL)")
    if agg_start == -1:
        raise SystemExit("all_test_issue_targets block not found in CMakeLists.txt")
    merged = merged[:agg_start] + "".join(invoke_lines) + "".join(agg_lines)
    return merged


def apply_cmake(profiles: dict[str, list[str]], dry_run: bool) -> None:
    new_text = prune_cmake_lists(profiles)
    if dry_run:
        print("would update CMakeLists.txt (bundle prune + aggregate)")
        return
    CMAKE_LISTS.write_text(new_text, encoding="utf-8")
    print(f"updated {CMAKE_LISTS.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if generated bundle outputs are stale",
    )
    parser.add_argument(
        "--migrate-sources",
        action="store_true",
        help="rename int main() to aura_issue_<stem>_run() in bundle member tests/",
    )
    parser.add_argument(
        "--apply-cmake",
        action="store_true",
        help="prune bundled issue targets from CMakeLists.txt and wire aggregate",
    )
    parser.add_argument(
        "--wrap-namespaces",
        action="store_true",
        help="wrap bundle member TUs in anonymous namespaces (link collision fix)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="with --migrate-sources, print files that would change without writing",
    )
    args = parser.parse_args()

    profiles = load_profiles()
    mains, cmake = generate_outputs()

    if args.migrate_sources:
        changed = migrate_member_sources(profiles, dry_run=args.dry_run)
        if changed:
            action = "would migrate" if args.dry_run else "migrated"
            print(f"{action} {len(changed)} member source(s):")
            for rel in changed:
                print(f"  {rel}")
        else:
            print("no member sources needed migration")
        if args.dry_run:
            return 0

    if args.apply_cmake:
        apply_cmake(profiles, dry_run=args.dry_run)
        return 0

    if args.wrap_namespaces:
        changed = wrap_bundle_members(profiles, dry_run=args.dry_run)
        if changed:
            action = "would wrap" if args.dry_run else "wrapped"
            print(f"{action} {len(changed)} member source(s) in anonymous namespaces")
        else:
            print("no member sources needed namespace wrap")
        return 0

    if args.check:
        errors = check_outputs(mains, cmake)
        if errors:
            for err in errors:
                print(f"stale: {err}", file=sys.stderr)
            return 1
        print("issue bundle outputs are up to date")
        return 0

    write_outputs(mains, cmake)
    print(f"wrote {len(mains)} bundle mains under {BUNDLES_DIR.relative_to(ROOT)}/")
    print(f"wrote {OUT_CMAKE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
