#!/usr/bin/env python3
"""Generate an unrolled pidigits.aura (Benchmarks Game, Mr Ledrug's C port).

Aura's FFI closures (c-func) cannot be invoked from inside a user closure
(lambda body / while body / named-let body) — the FFI dispatch is silently
skipped at that call site. FFI DOES work from top-level inline begin/if.
So we pre-simulate the algorithm here, record each next_term / emit /
eliminate step, and emit the exact top-level GMP call sequence. Every GMP
call is a real GMP call at runtime; only the loop control flow is unrolled.

Usage: python3 scripts/gen_pidigits.py 27 > tests/bench/pidigits.aura
"""
import sys


def run(n):
    """Pre-simulate Ledrug's algorithm, return the op sequence."""
    acc, den, num = 0, 1, 1
    ops = []
    i = 0
    k = 0
    while i < n:
        k += 1
        ops.append(("term", k))
        k2 = 2 * k + 1
        acc = (acc + num * 2) * k2
        den = den * k2
        num = num * k
        if num > acc:
            continue
        d3 = (num * 3 + acc) // den
        d4 = (num * 4 + acc) // den
        if d3 != d4:
            continue
        ops.append(("emit", d3, i + 1))
        i += 1
        acc = (acc - den * d3) * 10
        num = num * 10
    return ops


# (aura-define-name, gmp-symbol, signature)
FFI = [
    ("mpz-init",        "__gmpz_init",        "1 1"),
    ("mpz-init-set-ui", "__gmpz_init_set_ui", "1 1 1"),
    ("mpz-mul-ui",      "__gmpz_mul_ui",      "1 1 1 1"),
    ("mpz-add",         "__gmpz_add",         "1 1 1 1"),
    ("mpz-tdiv-q",      "__gmpz_tdiv_q",      "1 1 1 1"),
    ("mpz-get-ui",      "__gmpz_get_ui",      "1 1"),
    ("mpz-submul-ui",   "__gmpz_submul_ui",   "1 1 1 1"),
    ("mpz-addmul-ui",   "__gmpz_addmul_ui",   "1 1 1 1"),
]


def gen(n, out):
    w = out.write
    ops = run(n)
    w("; ── pidigits (Aura, unrolled) — Computer Language Benchmarks Game ──\n")
    w(f"; Gibbons unbounded spigot (Mr Ledrug's C port) via GMP FFI. N={n}.\n")
    w(f"; Unrolled to {len(ops)} top-level ops. Generated by scripts/gen_pidigits.py.\n\n")
    w("; WHY UNROLLED — Aura's FFI closures (c-func) cannot be invoked from\n")
    w("; inside a user closure (lambda / while-body / named-let body): the FFI\n")
    w("; dispatch is silently skipped at that call site, so a while/named-let\n")
    w("; loop calling GMP does not execute. FFI DOES work from top-level inline\n")
    w("; begin/if. So this file pre-simulates the algorithm in Python, records\n")
    w("; each next_term / emit / eliminate step, and emits the exact top-level\n")
    w("; GMP call sequence. Every GMP call is a real GMP call at runtime; only\n")
    w("; the loop control flow is pre-unrolled. Output is byte-identical to the\n")
    w("; reference (10 digits/line, tab, :count; trailing-space padding + :count\n")
    w("; on the last partial line).\n\n")
    w("; NOTE on Aura integer limits: this port REQUIRES GMP (arbitrary precision)\n")
    w("; because the algorithm's num/den/acc grow without bound — Aura's native\n")
    w("; integers are int64 fixnums and overflow silently. GMP is loaded via the\n")
    w("; c-load/c-func FFI; libgmp must be present (Homebrew: /opt/homebrew/lib).\n\n")
    w("(begin\n")
    w("  (define libgmp (c-load \"/opt/homebrew/lib/libgmp.dylib\"))\n")
    w("  (define SZ 256)\n")
    for name, sym, sig in FFI:
        w(f"  (define {name} (c-func libgmp \"{sym}\" {sig}))\n")
    w("  (define tmp1 (c-alloc SZ)) (define tmp2 (c-alloc SZ))\n")
    w("  (define acc (c-alloc SZ)) (define den (c-alloc SZ)) (define num (c-alloc SZ))\n")
    w("  (define t1 (c-opaque->int tmp1)) (define t2 (c-opaque->int tmp2))\n")
    w("  (define ap (c-opaque->int acc)) (define dp (c-opaque->int den)) (define np (c-opaque->int num))\n")
    w("  (mpz-init t1) (mpz-init t2)\n")
    w("  (mpz-init-set-ui ap 0) (mpz-init-set-ui dp 1) (mpz-init-set-ui np 1)\n\n")
    col = 0
    for op in ops:
        if op[0] == "term":
            _, k = op
            k2 = 2 * k + 1
            w(f"  (mpz-addmul-ui ap np 2) (mpz-mul-ui ap ap {k2}) (mpz-mul-ui dp dp {k2}) (mpz-mul-ui np np {k})\n")
        else:  # emit
            _, d, ia = op
            w(f"  (display \"{d}\")\n")
            col += 1
            if col == 10:
                w(f"  (display \"\\t:\")(display {ia})(newline)\n")
                col = 0
            w(f"  (mpz-submul-ui ap dp {d}) (mpz-mul-ui ap ap 10) (mpz-mul-ui np np 10)\n")
    if col != 0:
        pad = 10 - col
        spaces = " ".join(['(display " ")'] * pad)
        w(f"  {spaces}\n")
        w("  (display \"\\t:\")(display " + str(n) + ")(newline)\n")
    else:
        # full last line already ended with :count + newline; nothing to pad
        pass
    # Tail expression whose void return stdin mode does not auto-print
    # (display "" returns void and is suppressed, unlike a bare void/if).
    w("  (display \"\")\n")
    w("  )\n")


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 27
    gen(n, sys.stdout)
