#!/usr/bin/env python3
"""Generate docs from source (primitives, modules, stdlib).

Usage:
  python3 scripts/gen_docs.py          # write docs/generated/*.md
  python3 scripts/gen_docs.py --check  # fail if generated files are stale
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
STD = ROOT / "lib" / "std"
OUT = ROOT / "docs" / "generated"

GENERATED_BANNER = "<!-- AUTO-GENERATED by scripts/gen_docs.py — do not edit -->\n"

PRIMITIVE_RE = re.compile(r'primitives_\.add\s*\(\s*"([^"]+)"')
FFI_ADD_RE = re.compile(r'^\s+add\s*\(\s*"([^"]+)"', re.MULTILINE)
MODULE_RE = re.compile(r"^export\s+module\s+([\w.]+)\s*;", re.MULTILINE)
EXPORT_START_RE = re.compile(r"^\(export\b", re.MULTILINE)


@dataclass(frozen=True)
class Primitive:
    name: str
    file: str
    category: str = "core"  # Issue #559: classification tag
    deprecated: bool = False  # Issue #1438: surface deprecation in docs


# Issue #1434–#1437: names marked PrimMeta.deprecated in the engine.
# Keep in sync with mark_p1b_top_stats / query·mutate·workspace dispatch.
_DEPRECATED_CORE_ALIASES: frozenset[str] = frozenset(
    {
        # #1435 query
        "query:node",
        "query:children",
        "query:children-stable",
        "query:parent",
        "query:parent-stable",
        "query:find",
        "query:def-use",
        "query:mutation-log",
        # #1436 mutate
        "mutate:rebind",
        "mutate:replace-pattern",
        "mutate:replace-subtree",
        "mutate:replace-value",
        "mutate:replace-type",
        "mutate:move-node",
        "mutate:extract-function",
        "mutate:validate-against-schema",
        "mutate:atomic-batch",
        "mutate:sv-add-coverpoint",
        "mutate:sv-weaken-property",
        # #1437 workspace
        "workspace:create",
        "workspace:switch",
        "workspace:merge",
        "workspace:lock",
        "workspace:unlock",
        "workspace:list",
        "workspace:current",
    }
)

# #1434 top-20 stats (scripts/find_top_stats.py PINNED_TOP20)
try:
    import importlib.util

    _fts = ROOT / "scripts" / "find_top_stats.py"
    _spec = importlib.util.spec_from_file_location("find_top_stats", _fts)
    _mod = importlib.util.module_from_spec(_spec) if _spec and _spec.loader else None
    if _mod and _spec and _spec.loader:
        _spec.loader.exec_module(_mod)
        _DEPRECATED_TOP_STATS: frozenset[str] = frozenset(getattr(_mod, "PINNED_TOP20", []))
    else:
        _DEPRECATED_TOP_STATS = frozenset()
except Exception:  # noqa: BLE001 — docs gen must not fail on import noise
    _DEPRECATED_TOP_STATS = frozenset()

DEPRECATED_PRIMITIVES: frozenset[str] = _DEPRECATED_CORE_ALIASES | _DEPRECATED_TOP_STATS


def is_deprecated_name(name: str) -> bool:
    """Issue #1438: mark deprecated in generated primitives.md."""
    if name in DEPRECATED_PRIMITIVES:
        return True
    # Broad freeze-surface: all *-stats still public but discouraged
    return name.endswith("-stats") or name.endswith("-stats-hash") or "-stats-" in name


# Issue #559: 4-category classification (matches the issue's
# suggested taxonomy). Default-mapped from primitive name
# prefix; overrideable via docs/primitive_categories.yaml.
CATEGORY_PREFIX_MAP: dict[str, str] = {
    # mutation-safety: directly participate in mutate / guard /
    # workspace safety protocols. Must remain a primitive
    # per the decision framework red-line #2.
    "mutate:": "mutation-safety",
    "panic-": "mutation-safety",
    "panic:": "mutation-safety",
    "compile:": "mutation-safety",
    "workspace-": "mutation-safety",
    "set-code": "mutation-safety",
    "eval-current": "mutation-safety",
    "eval-with-recovery": "mutation-safety",
    "current-source": "mutation-safety",
    "api-reference": "mutation-safety",
    "workspace:": "mutation-safety",
    "ast:": "mutation-safety",
    # core: engine-boot dependencies + arithmetic + type
    # predicates + pair/string constructors. Red-line #1 + #3.
    "make-": "core",
    "cons": "core",
    "car": "core",
    "cdr": "core",
    "list": "core",
    "+": "core",
    "-": "core",
    "*": "core",
    "/": "core",
    "<": "core",
    "=": "core",
    "integer?": "core",
    "string?": "core",
    "pair?": "core",
    "list?": "core",
    "bool?": "core",
    "not": "core",
    "define": "core",
    "lambda": "core",
    "apply": "core",
    "eval": "core",
    "error?": "core",
    "nil": "core",
    # internal-observable: stats / counters / observability.
    # Decision framework §1 red-line #6 (observability is
    # required). Most can stay primitive (JSON protocol
    # contract) but could migrate to a sidecar observability
    # service in the future.
    "query:": "internal-observable",
    "snapshot": "internal-observable",
    "metrics": "internal-observable",
    # Hot-path string / vector / JSON (red-line #3) — language core,
    # NOT stdlib-only convenience. Issue #1440: do not demote these.
    "string-": "core",
    "string->": "core",
    "string=?": "core",
    "string<?": "core",
    "vector": "core",
    "list->vector": "core",
    "json-": "core",
    # Math builtins (floor/sin/…) are bare names → fall through to core.
    # Hash tables are language core (Agent / metrics / JSON objects).
    "hash-": "core",
    "hash->": "core",
    "make-hash": "core",
    # True convenience / product-layer wrappers (stdlib or demote candidates):
    "format": "convenience",
    "path-": "convenience",
    "time-": "convenience",
    "orchestrator": "convenience",
    "agent-": "convenience",
    "auto-evolve": "convenience",
    # Host / FFI boundary (red-line #4) — not "convenience".
    "c-": "mutation-safety",
    "ffi-": "mutation-safety",
    "file-": "mutation-safety",
    "git-": "mutation-safety",
}


def _load_category_overrides() -> dict[str, str]:
    """Load docs/primitive_categories.yaml if present.

    YAML format (one line per primitive):
      primitive-name: category
    Comments start with '#'. Categories must be one of:
    core, mutation-safety, internal-observable, convenience.
    """
    yaml_path = ROOT / "docs" / "primitive_categories.yaml"
    if not yaml_path.exists():
        return {}
    overrides: dict[str, str] = {}
    for line in yaml_path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if ":" not in s:
            continue
        name, _, cat = s.partition(":")
        name = name.strip()
        cat = cat.strip()
        if name and cat in {"core", "mutation-safety", "internal-observable", "convenience"}:
            overrides[name] = cat
    return overrides


def classify_primitive(name: str, overrides: dict[str, str]) -> str:
    """Map a primitive name to its category.

    Order of precedence:
      1. Explicit override (docs/primitive_categories.yaml)
      2. Prefix heuristic (CATEGORY_PREFIX_MAP)
      3. Default to 'core' (engine-boot guarantee)
    """
    if name in overrides:
        return overrides[name]
    # Longest-prefix match so "string->" wins over "string-" etc.
    best: str | None = None
    best_len = -1
    for prefix, cat in CATEGORY_PREFIX_MAP.items():
        if (name == prefix or name.startswith(prefix)) and len(prefix) > best_len:
            best = cat
            best_len = len(prefix)
    if best is not None:
        return best
    # Workspace boot dependencies default to mutation-safety.
    if name in {"set-code", "current-source", "eval-current", "api-reference"}:
        return "mutation-safety"
    # Issue #1440: bare hyphenated names are NOT auto-convenience.
    # Only explicit PREFIX_MAP / yaml overrides mark convenience;
    # unknown names default to core (safer for engine-boot red-line).
    return "core"


def scan_primitives() -> list[Primitive]:
    found: dict[str, Primitive] = {}
    overrides = _load_category_overrides()

    registrar_files = {"ffi_primitives_impl.cpp"}
    for path in sorted(SRC.rglob("*.cpp")):
        rel = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        use_registrar_add = path.name in registrar_files or path.name.startswith("evaluator_primitives_")
        if use_registrar_add:
            for m in FFI_ADD_RE.finditer(text):
                name = m.group(1)
                if name not in found:
                    found[name] = Primitive(
                        name,
                        rel,
                        classify_primitive(name, overrides),
                        is_deprecated_name(name),
                    )
        else:
            for m in PRIMITIVE_RE.finditer(text):
                name = m.group(1)
                if name not in found:
                    found[name] = Primitive(
                        name,
                        rel,
                        classify_primitive(name, overrides),
                        is_deprecated_name(name),
                    )

    return sorted(found.values(), key=lambda p: p.name)


def group_primitives(primitives: list[Primitive]) -> dict[str, list[Primitive]]:
    groups: dict[str, list[Primitive]] = defaultdict(list)
    for p in primitives:
        if ":" in p.name:
            key = p.name.split(":", 1)[0] + ":"
        elif p.name.startswith("c-"):
            key = "c-ffi"
        elif p.name in {
            "set-code",
            "current-source",
            "eval-current",
            "eval-current-output",
        }:
            key = "workspace-exec"
        else:
            key = "core"
        groups[key].append(p)
    return dict(sorted(groups.items(), key=lambda kv: (_group_order(kv[0]), kv[0])))


def _group_order(key: str) -> int:
    order = [
        "workspace-exec",
        "query:",
        "mutate:",
        "ast:",
        "workspace:",
        "fiber:",
        "agent:",
        "session:",
        "synthesize:",
        "compile:",
        "c-ffi",
        "core",
    ]
    try:
        return order.index(key)
    except ValueError:
        return len(order)


def render_primitives(primitives: list[Primitive]) -> str:
    # Issue #559: 4-category grouping (decision-framework
    # taxonomy). Display category buckets in a stable order.
    CATEGORY_ORDER = ["mutation-safety", "core", "internal-observable", "convenience"]
    CATEGORY_TITLE = {
        "mutation-safety": "Mutation safety (must remain primitive)",
        "core": "Core builtins (must remain primitive)",
        "internal-observable": "Internal observable (stats/counters)",
        "convenience": "Convenience (candidates for stdlib migration)",
    }
    by_cat: dict[str, list[Primitive]] = {c: [] for c in CATEGORY_ORDER}
    for p in primitives:
        cat = p.category if p.category in by_cat else "core"
        by_cat[cat].append(p)
    n_dep = sum(1 for p in primitives if p.deprecated)
    lines = [
        GENERATED_BANNER,
        "# Primitives (generated)",
        "",
        f"**{len(primitives)}** registrations scanned from `src/**/*.cpp` "
        f"({n_dep} marked **deprecated** — Issue #1438).",
        "Runtime canonical list: `(api-reference)` (includes `*deprecated*` section).",
        "Prefer op-dispatch: `(query :op)` `(mutate :op)` `(workspace :op)` + `(engine:metrics)`.",
        "",
        "**Classification (Issue #559)**:",
        "",
    ]
    for cat in CATEGORY_ORDER:
        n = len(by_cat[cat])
        total = len(primitives)
        pct = (100.0 * n / total) if total else 0.0
        lines.append(f"- **{cat}**: {n} primitives ({pct:.0f}%)")
    lines.append("")
    lines.append(
        "Categories follow the taxonomy in "
        "[design/primitive-vs-stdlib-decision-framework.md]"
        "(design/primitive-vs-stdlib-decision-framework.md). "
        "Override per-primitive classifications via "
        "`docs/primitive_categories.yaml`."
    )
    lines.append("")

    def _fmt_line(p: Primitive, with_cat: bool = True) -> str:
        dep = " **deprecated**" if p.deprecated else ""
        if with_cat:
            return f"- `{p.name}` *[{p.category}]*{dep} — `{p.file}`"
        return f"- `{p.name}`{dep} — `{p.file}`"

    # Legacy group-by-prefix rendering (kept for backward
    # compat with the existing primitives.md layout).
    groups = group_primitives(primitives)
    for group, items in groups.items():
        title = {
            "workspace-exec": "Workspace load / eval",
            "c-ffi": "C FFI",
            "core": "Core builtins",
        }.get(group, group.rstrip(":").title() + (":" if group.endswith(":") else ""))
        lines.append(f"## {title} ({len(items)})")
        lines.append("")
        for p in items:
            lines.append(_fmt_line(p, with_cat=True))
        lines.append("")
    # New: 4-category section (Issue #559 primary deliverable).
    lines.append("## By category (Issue #559)")
    lines.append("")
    for cat in CATEGORY_ORDER:
        items = by_cat[cat]
        if not items:
            continue
        lines.append(f"### {CATEGORY_TITLE[cat]} ({len(items)})")
        lines.append("")
        for p in items:
            lines.append(_fmt_line(p, with_cat=False))
        lines.append("")
    # Issue #1438: collapsed deprecated index
    dep_items = [p for p in primitives if p.deprecated]
    if dep_items:
        lines.append("## Deprecated (Issue #1438)")
        lines.append("")
        lines.append(
            "Still registered for compatibility. Prefer "
            "`(query :op)` / `(mutate :op)` / `(workspace :op)` / `(engine:metrics)`. "
            f"**{len(dep_items)}** names:"
        )
        lines.append("")
        for p in dep_items:
            lines.append(f"- `{p.name}` — `{p.file}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def scan_modules() -> list[tuple[str, str]]:
    mods: list[tuple[str, str]] = []
    for path in sorted(SRC.rglob("*.ixx")):
        text = path.read_text(encoding="utf-8", errors="replace")
        m = MODULE_RE.search(text)
        if m:
            mods.append((m.group(1), path.relative_to(ROOT).as_posix()))
    return sorted(mods, key=lambda x: x[0])


def render_modules(modules: list[tuple[str, str]]) -> str:
    lines = [
        GENERATED_BANNER,
        "# C++ Modules (generated)",
        "",
        f"**{len(modules)}** `export module` declarations in `src/**/*.ixx`.",
        "",
        "| Module | File |",
        "|--------|------|",
    ]
    for name, path in modules:
        lines.append(f"| `{name}` | `{path}` |")
    lines.append("")
    return "\n".join(lines)


def parse_export_symbols(text: str) -> list[str]:
    symbols: list[str] = []
    for m in EXPORT_START_RE.finditer(text):
        start = m.end()
        depth = 1
        i = start
        while i < len(text) and depth > 0:
            if text[i] == "(":
                depth += 1
            elif text[i] == ")":
                depth -= 1
            i += 1
        body = text[start : i - 1].strip()
        if not body:
            continue
        for tok in re.split(r"\s+", body):
            tok = tok.strip()
            if tok and tok not in symbols:
                symbols.append(tok)
    return symbols


def scan_stdlib() -> list[tuple[str, str, list[str]]]:
    rows: list[tuple[str, str, list[str]]] = []
    for path in sorted(STD.glob("*.aura")):
        text = path.read_text(encoding="utf-8", errors="replace")
        desc = ""
        for line in text.splitlines():
            s = line.strip()
            if s.startswith(";") and not s.startswith("; ──"):
                desc = s.lstrip("; ").strip()
                break
            if s.startswith("(define") or s.startswith("(export"):
                break
        exports = parse_export_symbols(text)
        rows.append((path.stem, desc, exports))
    return rows


def render_stdlib(rows: list[tuple[str, str, list[str]]]) -> str:
    lines = [
        GENERATED_BANNER,
        "# Standard library index (generated)",
        "",
        f'**{len(rows)}** modules in `lib/std/`. Load: `(require "std/name" all:)`.',
        "",
        "| Module | Exports | Description |",
        "|--------|---------|-------------|",
    ]
    for name, desc, exports in rows:
        exp = " ".join(f"`{e}`" for e in exports[:8])
        if len(exports) > 8:
            exp += f" … (+{len(exports) - 8})"
        if not exp:
            exp = "—"
        desc_cell = desc.replace("|", "\\|") if desc else "—"
        lines.append(f"| `std/{name}` | {exp} | {desc_cell} |")
    lines.append("")
    return "\n".join(lines)


def write_outputs() -> dict[str, str]:
    primitives = scan_primitives()
    modules = scan_modules()
    stdlib = scan_stdlib()
    return {
        "primitives.md": render_primitives(primitives),
        "modules.md": render_modules(modules),
        "stdlib-index.md": render_stdlib(stdlib),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/generated/*.md would change",
    )
    args = parser.parse_args()

    outputs = write_outputs()
    OUT.mkdir(parents=True, exist_ok=True)

    stale: list[str] = []
    for name, content in outputs.items():
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"  wrote {path.relative_to(ROOT)} ({len(content)} bytes)")

    if args.check:
        if stale:
            print("Generated docs are stale:", ", ".join(stale), file=sys.stderr)
            print("Run: python3 scripts/gen_docs.py", file=sys.stderr)
            return 1
        print("Generated docs OK")
        return 0

    print(f"Generated {len(outputs)} files under docs/generated/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
