#!/usr/bin/env python3
"""Generate docs from source (primitives, modules, stdlib).

Usage:
  python3 scripts/gen_docs.py          # write docs/generated/*.md
  python3 scripts/gen_docs.py --check  # fail if generated files are stale
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
STD = ROOT / "lib" / "std"
OUT = ROOT / "docs" / "generated"

GENERATED_BANNER = "<!-- AUTO-GENERATED by scripts/gen_docs.py — do not edit -->\n"

PRIMITIVE_RE = re.compile(r'primitives_\.add\s*\(\s*"([^"]+)"')
FFI_ADD_RE = re.compile(r'^\s+add\s*\(\s*"([^"]+)"', re.MULTILINE)
MODULE_RE = re.compile(r"^export\s+module\s+([\w.]+)\s*;", re.MULTILINE)
EXPORT_START_RE = re.compile(r"^\(export\b", re.MULTILINE)


@dataclass(frozen=True)
class Primitive:
    name: str
    file: str


def scan_primitives() -> list[Primitive]:
    found: dict[str, Primitive] = {}

    registrar_files = {"ffi_primitives_impl.cpp"}
    for path in sorted(SRC.rglob("*.cpp")):
        rel = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        use_registrar_add = path.name in registrar_files or path.name.startswith("evaluator_primitives_")
        if use_registrar_add:
            for m in FFI_ADD_RE.finditer(text):
                name = m.group(1)
                found.setdefault(name, Primitive(name, rel))
        else:
            for m in PRIMITIVE_RE.finditer(text):
                name = m.group(1)
                found.setdefault(name, Primitive(name, rel))

    return sorted(found.values(), key=lambda p: p.name)


def group_primitives(primitives: list[Primitive]) -> dict[str, list[Primitive]]:
    groups: dict[str, list[Primitive]] = defaultdict(list)
    for p in primitives:
        if ":" in p.name:
            key = p.name.split(":", 1)[0] + ":"
        elif p.name.startswith("c-"):
            key = "c-ffi"
        elif p.name in {
            "set-code",
            "current-source",
            "eval-current",
            "eval-current-output",
        }:
            key = "workspace-exec"
        else:
            key = "core"
        groups[key].append(p)
    return dict(sorted(groups.items(), key=lambda kv: (_group_order(kv[0]), kv[0])))


def _group_order(key: str) -> int:
    order = [
        "workspace-exec",
        "query:",
        "mutate:",
        "ast:",
        "workspace:",
        "fiber:",
        "agent:",
        "session:",
        "synthesize:",
        "compile:",
        "c-ffi",
        "core",
    ]
    try:
        return order.index(key)
    except ValueError:
        return len(order)


def render_primitives(primitives: list[Primitive]) -> str:
    groups = group_primitives(primitives)
    lines = [
        GENERATED_BANNER,
        "# Primitives (generated)",
        "",
        f"**{len(primitives)}** registrations scanned from `src/**/*.cpp`.",
        "Runtime canonical list: `(api-reference)`.",
        "",
    ]
    for group, items in groups.items():
        title = {
            "workspace-exec": "Workspace load / eval",
            "c-ffi": "C FFI",
            "core": "Core builtins",
        }.get(group, group.rstrip(":").title() + (":" if group.endswith(":") else ""))
        lines.append(f"## {title} ({len(items)})")
        lines.append("")
        for p in items:
            lines.append(f"- `{p.name}` — `{p.file}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def scan_modules() -> list[tuple[str, str]]:
    mods: list[tuple[str, str]] = []
    for path in sorted(SRC.rglob("*.ixx")):
        text = path.read_text(encoding="utf-8", errors="replace")
        m = MODULE_RE.search(text)
        if m:
            mods.append((m.group(1), path.relative_to(ROOT).as_posix()))
    return sorted(mods, key=lambda x: x[0])


def render_modules(modules: list[tuple[str, str]]) -> str:
    lines = [
        GENERATED_BANNER,
        "# C++ Modules (generated)",
        "",
        f"**{len(modules)}** `export module` declarations in `src/**/*.ixx`.",
        "",
        "| Module | File |",
        "|--------|------|",
    ]
    for name, path in modules:
        lines.append(f"| `{name}` | `{path}` |")
    lines.append("")
    return "\n".join(lines)


def parse_export_symbols(text: str) -> list[str]:
    symbols: list[str] = []
    for m in EXPORT_START_RE.finditer(text):
        start = m.end()
        depth = 1
        i = start
        while i < len(text) and depth > 0:
            if text[i] == "(":
                depth += 1
            elif text[i] == ")":
                depth -= 1
            i += 1
        body = text[start : i - 1].strip()
        if not body:
            continue
        for tok in re.split(r"\s+", body):
            tok = tok.strip()
            if tok and tok not in symbols:
                symbols.append(tok)
    return symbols


def scan_stdlib() -> list[tuple[str, str, list[str]]]:
    rows: list[tuple[str, str, list[str]]] = []
    for path in sorted(STD.glob("*.aura")):
        text = path.read_text(encoding="utf-8", errors="replace")
        desc = ""
        for line in text.splitlines():
            s = line.strip()
            if s.startswith(";") and not s.startswith("; ──"):
                desc = s.lstrip("; ").strip()
                break
            if s.startswith("(define") or s.startswith("(export"):
                break
        exports = parse_export_symbols(text)
        rows.append((path.stem, desc, exports))
    return rows


def render_stdlib(rows: list[tuple[str, str, list[str]]]) -> str:
    lines = [
        GENERATED_BANNER,
        "# Standard library index (generated)",
        "",
        f'**{len(rows)}** modules in `lib/std/`. Load: `(require "std/name" all:)`.',
        "",
        "| Module | Exports | Description |",
        "|--------|---------|-------------|",
    ]
    for name, desc, exports in rows:
        exp = " ".join(f"`{e}`" for e in exports[:8])
        if len(exports) > 8:
            exp += f" … (+{len(exports) - 8})"
        if not exp:
            exp = "—"
        desc_cell = desc.replace("|", "\\|") if desc else "—"
        lines.append(f"| `std/{name}` | {exp} | {desc_cell} |")
    lines.append("")
    return "\n".join(lines)


def write_outputs() -> dict[str, str]:
    primitives = scan_primitives()
    modules = scan_modules()
    stdlib = scan_stdlib()
    return {
        "primitives.md": render_primitives(primitives),
        "modules.md": render_modules(modules),
        "stdlib-index.md": render_stdlib(stdlib),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/generated/*.md would change",
    )
    args = parser.parse_args()

    outputs = write_outputs()
    OUT.mkdir(parents=True, exist_ok=True)

    stale: list[str] = []
    for name, content in outputs.items():
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"  wrote {path.relative_to(ROOT)} ({len(content)} bytes)")

    if args.check:
        if stale:
            print("Generated docs are stale:", ", ".join(stale), file=sys.stderr)
            print("Run: python3 scripts/gen_docs.py", file=sys.stderr)
            return 1
        print("Generated docs OK")
        return 0

    print(f"Generated {len(outputs)} files under docs/generated/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
