#!/usr/bin/env python3
"""Generate src/compiler/compiler_metrics_fields.inc from observability_metrics.h."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HDR = ROOT / "src/compiler/observability_metrics.h"
OUT = ROOT / "src/compiler/compiler_metrics_fields.inc"


def main() -> int:
    text = HDR.read_text(encoding="utf-8")
    start = text.index("struct CompilerMetrics")
    end = text.index("struct FnMetrics")
    body = text[start:end]
    fields = re.findall(r"std::atomic<\s*std::uint64_t\s*>\s+(\w+)\s*\{", body)
    lines = [
        "// AUTO-GENERATED by scripts/gen_compiler_metrics_fields.py — do not edit",
        f"// {len(fields)} CompilerMetrics atomic fields",
        "#ifndef AURA_COMPILER_METRICS_FIELD",
        '#error "define AURA_COMPILER_METRICS_FIELD(name) before including"',
        "#endif",
        "",
    ]
    for f in fields:
        lines.append(f"AURA_COMPILER_METRICS_FIELD({f})")
    lines.append("")
    lines.append("#undef AURA_COMPILER_METRICS_FIELD")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(fields)} fields)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
