#!/usr/bin/env python3
"""Issue #1453: generate lightweight TestRegistry catalog from test sources.

Scans tests/test_*.cpp for @category / @reason headers and writes
docs/generated/test-registry.json.

Usage:
  python3 scripts/gen_test_registry.py           # write
  python3 scripts/gen_test_registry.py --check   # fail if stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "generated" / "test-registry.json"

CAT_RE = re.compile(r"^//\s*@category:\s*(\S+)", re.M)
REASON_RE = re.compile(r"^//\s*@reason:\s*(.+)$", re.M)
ISSUE_RE = re.compile(r"test_issue_(\d+)")


def scan() -> dict:
    entries: list[dict] = []
    # Phase 1 of the tests/ consolidation (Anqi 05:43 directive):
    # scan both tests/ root and tests/issues/ subdirectory so per-issue
    # tests moved into tests/issues/ are still picked up.
    # #1957: also scan theme dirs (mutation/fiber/observability/…) where
    # issue tests are folded into *_batch.cpp drivers.
    tests_dir = ROOT / "tests"
    issue_subdir = tests_dir / "issues"
    domain_dir = tests_dir / "domain"
    candidates: list[Path] = []
    candidates.extend(sorted(tests_dir.glob("test_*.cpp")))
    if issue_subdir.is_dir():
        candidates.extend(sorted(issue_subdir.glob("test_*.cpp")))
    # Domain suites + theme pilots (e.g. domain/arena/, #1959)
    if domain_dir.is_dir():
        candidates.extend(sorted(domain_dir.glob("test_*.cpp")))
        candidates.extend(sorted(domain_dir.glob("*/test_*.cpp")))
    # Theme family batches under tests/<theme>/test_*.cpp (#1957 folds)
    for theme_dir in sorted(tests_dir.iterdir()):
        if not theme_dir.is_dir():
            continue
        name = theme_dir.name
        if name in {"issues", "domain", "python", "fixtures", "bundles", "cases"}:
            continue
        if name.startswith("."):
            continue
        candidates.extend(sorted(theme_dir.glob("test_*.cpp")))
    for path in sorted(set(candidates)):
        try:
            head = path.read_text(encoding="utf-8", errors="replace")[:4000]
        except OSError:
            continue
        cat_m = CAT_RE.search(head)
        reason_m = REASON_RE.search(head)
        issue_m = ISSUE_RE.search(path.name)
        # emit path relative to repo root (tests/... or tests/issues/...)
        rel = path.relative_to(ROOT).as_posix()
        entries.append(
            {
                "file": rel,
                "category": cat_m.group(1) if cat_m else "unknown",
                "reason": reason_m.group(1).strip() if reason_m else "",
                "issue": int(issue_m.group(1)) if issue_m else None,
            }
        )

    by_cat: dict[str, int] = {}
    for e in entries:
        by_cat[e["category"]] = by_cat.get(e["category"], 0) + 1

    return {
        "schema": 1,
        "note": "Issue #1453 lightweight TestRegistry — generated by scripts/gen_test_registry.py",
        "count": len(entries),
        "by_category": dict(sorted(by_cat.items())),
        "tests": entries,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if registry is stale")
    ap.add_argument("--write", action="store_true", help="write registry (default)")
    args = ap.parse_args()
    data = scan()
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"FAIL: missing {OUT.relative_to(ROOT)}; run gen_test_registry.py", file=sys.stderr)
            return 1
        old = OUT.read_text(encoding="utf-8")
        # Compare counts + file list for stability (ignore reason text drift)
        old_j = json.loads(old)
        old_files = {t["file"] for t in old_j.get("tests", [])}
        new_files = {t["file"] for t in data["tests"]}
        if old_files != new_files or old_j.get("count") != data["count"]:
            print(
                f"FAIL: test-registry.json stale (count {old_j.get('count')}→{data['count']}).\n"
                f"  Run: python3 scripts/gen_test_registry.py\n"
                f"  And commit docs/generated/test-registry.json",
                file=sys.stderr,
            )
            return 1
        print(f"OK: test-registry.json up to date ({data['count']} tests)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({data['count']} tests, categories={data['by_category']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
