# CMake generated Testfile for 
# Source directory: /home/dev/code/aura
# Build directory: /home/dev/code/aura/build_gdb
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[step09_int_42]=] "sh" "-c" "test \"\$(printf '42' | ./aura)\" = 42")
set_tests_properties([=[step09_int_42]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;100;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step09_int_neg5]=] "sh" "-c" "test \"\$(printf '(- 5 10)' | ./aura)\" = -5")
set_tests_properties([=[step09_int_neg5]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;101;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step10_var_error]=] "sh" "-c" "echo x | ./aura 2>&1 | grep -F 'unbound variable'")
set_tests_properties([=[step10_var_error]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;102;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step10_let]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) x)' | ./aura)\" = 10")
set_tests_properties([=[step10_let]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;105;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step10_let_nested]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) (let ((x 20)) x))' | ./aura)\" = 20")
set_tests_properties([=[step10_let_nested]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;106;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_add]=] "sh" "-c" "test \"\$(printf '(+ 1 2)' | ./aura)\" = 3")
set_tests_properties([=[step11_add]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;107;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_sub]=] "sh" "-c" "test \"\$(printf '(- 5 3)' | ./aura)\" = 2")
set_tests_properties([=[step11_sub]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;108;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_mul]=] "sh" "-c" "test \"\$(printf '(* 2 3)' | ./aura)\" = 6")
set_tests_properties([=[step11_mul]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;109;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step11_nested]=] "sh" "-c" "test \"\$(printf '(+ 1 (* 2 3))' | ./aura)\" = 7")
set_tests_properties([=[step11_nested]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;110;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step12_if_true]=] "sh" "-c" "test \"\$(printf '(if 1 42 0)' | ./aura)\" = 42")
set_tests_properties([=[step12_if_true]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;111;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step12_if_false]=] "sh" "-c" "test \"\$(printf '(if 0 0 99)' | ./aura)\" = 99")
set_tests_properties([=[step12_if_false]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;112;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step15_letrec_fact5]=] "sh" "-c" "test \"\$(printf '(letrec ((fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))) (fact 5))' | ./aura)\" = 120")
set_tests_properties([=[step15_letrec_fact5]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;113;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[step15_letrec_fact10]=] "sh" "-c" "test \"\$(printf '(letrec ((fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))) (fact 10))' | ./aura)\" = 3628800")
set_tests_properties([=[step15_letrec_fact10]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;96;add_test;/home/dev/code/aura/CMakeLists.txt;115;AT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_basic]=] "./test_ir")
set_tests_properties([=[ir_basic]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;166;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_int_42]=] "sh" "-c" "test \"\$(printf '42' | ./aura --ir)\" = 42")
set_tests_properties([=[ir_int_42]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;175;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_add_1_2]=] "sh" "-c" "test \"\$(printf '(+ 1 2)' | ./aura --ir)\" = 3")
set_tests_properties([=[ir_add_1_2]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;176;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_mul_2_3]=] "sh" "-c" "test \"\$(printf '(* 2 3)' | ./aura --ir)\" = 6")
set_tests_properties([=[ir_mul_2_3]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;177;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_if_true]=] "sh" "-c" "test \"\$(printf '(if 1 42 0)' | ./aura --ir)\" = 42")
set_tests_properties([=[ir_if_true]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;178;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_if_false]=] "sh" "-c" "test \"\$(printf '(if 0 0 99)' | ./aura --ir)\" = 99")
set_tests_properties([=[ir_if_false]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;179;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_let_x]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) x)' | ./aura --ir)\" = 10")
set_tests_properties([=[ir_let_x]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;180;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_lambda_call]=] "sh" "-c" "test \"\$(printf '((lambda (x) (* x 2)) 5)' | ./aura --ir)\" = 10")
set_tests_properties([=[ir_lambda_call]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;181;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[ir_lambda_closure]=] "sh" "-c" "test \"\$(printf '(let ((x 10)) ((lambda (y) (+ x y)) 5))' | ./aura --ir)\" = 15")
set_tests_properties([=[ir_lambda_closure]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;171;add_test;/home/dev/code/aura/CMakeLists.txt;182;IRT;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_query_call]=] "sh" "-c" "printf '(+ 1 2)' | ./aura --query '(node-type Call)' | grep -q '1 matches'")
set_tests_properties([=[cli_query_call]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;186;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_query_callee]=] "sh" "-c" "printf '(+ 1 2)' | ./aura --query '(callee \"+\")' | grep -q '1 matches'")
set_tests_properties([=[cli_query_callee]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;191;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_query_and_fix]=] "sh" "-c" "printf '(+ 1 2)' | ./aura --query-and-fix '(node-type LiteralInt)' '(LiteralInt 99)' | grep -q 'applied=true'")
set_tests_properties([=[cli_query_and_fix]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;196;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_auto_fix]=] "sh" "-c" "printf '(+ 1 2)' | timeout 10 ./aura --auto-fix | grep -q 'auto-fix'")
set_tests_properties([=[cli_auto_fix]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;201;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_serve_error]=] "sh" "-c" "printf '(+ x 1)' | timeout 5 ./aura --serve | grep -q -F 'kind'")
set_tests_properties([=[cli_serve_error]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;206;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[cli_serve_ok]=] "sh" "-c" "printf '(+ 1 2)' | timeout 5 ./aura --serve | grep -q -F 'ok'")
set_tests_properties([=[cli_serve_ok]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;209;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[tc_int]=] "sh" "-c" "printf '42' | timeout 5 ./aura --typecheck | grep -q 'type: Int'")
set_tests_properties([=[tc_int]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;212;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[tc_lambda]=] "sh" "-c" "printf '(lambda (x) x)' | timeout 5 ./aura --typecheck | grep -q -e '->'")
set_tests_properties([=[tc_lambda]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;215;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
add_test([=[tc_let]=] "sh" "-c" "printf '(let ((x 10)) x)' | timeout 5 ./aura --typecheck | grep -q 'type: Int'")
set_tests_properties([=[tc_let]=] PROPERTIES  WORKING_DIRECTORY "/home/dev/code/aura/build_gdb" _BACKTRACE_TRIPLES "/home/dev/code/aura/CMakeLists.txt;218;add_test;/home/dev/code/aura/CMakeLists.txt;0;")
