// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle driver for profile: jit_late5

#include <cstdio>
#include <cstdlib>
#include <sys/wait.h>
#include <unistd.h>

#include "test_harness.hpp"

extern "C" void aura_reset_runtime();

extern int aura_issue_637_run();
extern int aura_issue_640_run();
extern int aura_issue_641_run();
extern int aura_issue_642_run();
extern int aura_issue_643_run();
extern int aura_issue_644_run();
extern int aura_issue_645_run();
extern int aura_issue_646_run();
extern int aura_issue_647_run();
extern int aura_issue_648_run();
extern int aura_issue_649_run();
extern int aura_issue_650_run();
extern int aura_issue_651_run();
extern int aura_issue_589_run();
extern int aura_issue_590_run();
extern int aura_issue_479_run();
extern int aura_issue_464_arena_auto_compaction_run();
extern int aura_issue_465_cxx26_hotpath_run();
extern int aura_issue_470_stable_ref_sv_scale_run();
extern int aura_issue_471_dirty_sv_scale_run();

int main() {
    struct Member {
        const char* name;
        int (*run)();
    };
    Member members[] = {
        {"test_issue_637", aura_issue_637_run},
        {"test_issue_640", aura_issue_640_run},
        {"test_issue_641", aura_issue_641_run},
        {"test_issue_642", aura_issue_642_run},
        {"test_issue_643", aura_issue_643_run},
        {"test_issue_644", aura_issue_644_run},
        {"test_issue_645", aura_issue_645_run},
        {"test_issue_646", aura_issue_646_run},
        {"test_issue_647", aura_issue_647_run},
        {"test_issue_648", aura_issue_648_run},
        {"test_issue_649", aura_issue_649_run},
        {"test_issue_650", aura_issue_650_run},
        {"test_issue_651", aura_issue_651_run},
        {"test_issue_589", aura_issue_589_run},
        {"test_issue_590", aura_issue_590_run},
        {"test_issue_479", aura_issue_479_run},
        {"test_issue_464_arena_auto_compaction", aura_issue_464_arena_auto_compaction_run},
        {"test_issue_465_cxx26_hotpath", aura_issue_465_cxx26_hotpath_run},
        {"test_issue_470_stable_ref_sv_scale", aura_issue_470_stable_ref_sv_scale_run},
        {"test_issue_471_dirty_sv_scale", aura_issue_471_dirty_sv_scale_run},
    };

    int passed = 0;
    int failed = 0;
    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));

    for (int i = 0; i < n_members; ++i) {
        std::println("\n════ Bundle member: {} ════", members[i].name);
        ::aura::test::g_passed = 0;
        ::aura::test::g_failed = 0;
        const pid_t pid = ::fork();
        if (pid < 0) {
            std::println(std::cerr, "fork failed for {}", members[i].name);
            ++failed;
            continue;
        }
        if (pid == 0) {
            aura_reset_runtime();
            const int rc = members[i].run();
            std::fflush(nullptr);
            ::_exit(rc == 0 ? 0 : 1);
        }
        int status = 0;
        if (::waitpid(pid, &status, 0) < 0) {
            std::println(std::cerr, "waitpid failed for {}", members[i].name);
            ++failed;
            continue;
        }
        if (WIFEXITED(status) && WEXITSTATUS(status) == 0) {
            ++passed;
        } else {
            ++failed;
            if (WIFSIGNALED(status)) {
                std::println(std::cerr, "bundle member {} crashed signal={}", members[i].name,
                             WTERMSIG(status));
            } else {
                std::println(std::cerr, "bundle member {} failed (rc={})", members[i].name,
                             WIFEXITED(status) ? WEXITSTATUS(status) : -1);
            }
        }
    }

    std::println("──────────────────────────────────────");
    std::println("Total: {} passed, {} failed", passed, failed);
    return failed > 0 ? 1 : 0;
}
