// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle driver for profile: jit

#include <cstdio>

#include "test_harness.hpp"

extern int aura_issue_135_run();
extern int aura_issue_137_run();
extern int aura_issue_158_run();
extern int aura_issue_159_run();
extern int aura_issue_184_run();
extern int aura_issue_165_run();
extern int aura_issue_166_run();
extern int aura_issue_169_run();
extern int aura_issue_138_run();
extern int aura_issue_139_run();
extern int aura_issue_140_run();
extern int aura_issue_141_run();
extern int aura_issue_142_run();
extern int aura_issue_143_run();
extern int aura_issue_145_run();
extern int aura_issue_187_run();
extern int aura_issue_188_run();
extern int aura_issue_189_run();
extern int aura_issue_190_run();
extern int aura_issue_191_run();
extern int aura_issue_192_run();
extern int aura_issue_193_run();
extern int aura_issue_194_run();
extern int aura_issue_196_run();
extern int aura_issue_247_run();
extern int aura_issue_248_run();
extern int aura_issue_249_run();
extern int aura_issue_250_run();
extern int aura_issue_197_observability_run();
extern int aura_issue_227_run();
extern int aura_issue_240_run();
extern int aura_issue_260_run();
extern int aura_issue_242_run();
extern int aura_issue_244_run();
extern int aura_issue_228_run();

int main() {
    struct Member {
        const char* name;
        int (*run)();
    };
    Member members[] = {
        {"test_issue_135", aura_issue_135_run},
        {"test_issue_137", aura_issue_137_run},
        {"test_issue_158", aura_issue_158_run},
        {"test_issue_159", aura_issue_159_run},
        {"test_issue_184", aura_issue_184_run},
        {"test_issue_165", aura_issue_165_run},
        {"test_issue_166", aura_issue_166_run},
        {"test_issue_169", aura_issue_169_run},
        {"test_issue_138", aura_issue_138_run},
        {"test_issue_139", aura_issue_139_run},
        {"test_issue_140", aura_issue_140_run},
        {"test_issue_141", aura_issue_141_run},
        {"test_issue_142", aura_issue_142_run},
        {"test_issue_143", aura_issue_143_run},
        {"test_issue_145", aura_issue_145_run},
        {"test_issue_187", aura_issue_187_run},
        {"test_issue_188", aura_issue_188_run},
        {"test_issue_189", aura_issue_189_run},
        {"test_issue_190", aura_issue_190_run},
        {"test_issue_191", aura_issue_191_run},
        {"test_issue_192", aura_issue_192_run},
        {"test_issue_193", aura_issue_193_run},
        {"test_issue_194", aura_issue_194_run},
        {"test_issue_196", aura_issue_196_run},
        {"test_issue_247", aura_issue_247_run},
        {"test_issue_248", aura_issue_248_run},
        {"test_issue_249", aura_issue_249_run},
        {"test_issue_250", aura_issue_250_run},
        {"test_issue_197_observability", aura_issue_197_observability_run},
        {"test_issue_227", aura_issue_227_run},
        {"test_issue_240", aura_issue_240_run},
        {"test_issue_260", aura_issue_260_run},
        {"test_issue_242", aura_issue_242_run},
        {"test_issue_244", aura_issue_244_run},
        {"test_issue_228", aura_issue_228_run},
    };

    int passed = 0;
    int failed = 0;
    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));

    for (int i = 0; i < n_members; ++i) {
        std::fprintf(stdout, "\n════ Bundle member: %s ════\n", members[i].name);
        const int rc = members[i].run();
        if (rc == 0) {
            ++passed;
        } else {
            ++failed;
        }
    }

    std::fprintf(stdout, "──────────────────────────────────────\n");
    std::fprintf(stdout, "Total: %d passed, %d failed\n", passed, failed);
    return failed > 0 ? 1 : 0;
}
