// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle driver for profile: jit_tests

#include <cstdio>

#include "test_harness.hpp"

extern int aura_issue_224_run();
extern int aura_issue_224_closure_bridge_run();
extern int aura_issue_225_bridge_invalidation_run();
extern int aura_issue_226_run();

int main() {
    struct Member {
        const char* name;
        int (*run)();
    };
    Member members[] = {
        {"test_issue_224", aura_issue_224_run},
        {"test_issue_224_closure_bridge", aura_issue_224_closure_bridge_run},
        {"test_issue_225_bridge_invalidation", aura_issue_225_bridge_invalidation_run},
        {"test_issue_226", aura_issue_226_run},
    };

    int passed = 0;
    int failed = 0;
    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));

    for (int i = 0; i < n_members; ++i) {
        std::fprintf(stdout, "\n════ Bundle member: %s ════\n", members[i].name);
        ::aura::test::g_passed = 0;
        ::aura::test::g_failed = 0;
        const int rc = members[i].run();
        if (rc == 0) {
            ++passed;
        } else {
            ++failed;
        }
    }

    std::fprintf(stdout, "──────────────────────────────────────\n");
    std::fprintf(stdout, "Total: %d passed, %d failed\n", passed, failed);
    return failed > 0 ? 1 : 0;
}
