// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late5
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"


int main() {
    return aura_run_issue_bundle("jit_late5", nullptr, 0);
}
