// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_tests
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_401_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_401", aura_issue_401_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_tests", members, n);
}
