// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle driver for profile: fiber

#include <cstdio>
#include <cstdlib>
#include <sys/wait.h>
#include <unistd.h>

#include "test_harness.hpp"

extern "C" void aura_reset_runtime();

extern int aura_issue_115_run();
extern int aura_issue_204_run();
extern int aura_issue_205_run();

int main() {
    struct Member {
        const char* name;
        int (*run)();
    };
    Member members[] = {
        {"test_issue_115", aura_issue_115_run},
        {"test_issue_204", aura_issue_204_run},
        {"test_issue_205", aura_issue_205_run},
    };

    int passed = 0;
    int failed = 0;
    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));

    for (int i = 0; i < n_members; ++i) {
        std::println("\n════ Bundle member: {} ════", members[i].name);
        ::aura::test::g_passed = 0;
        ::aura::test::g_failed = 0;
        const pid_t pid = ::fork();
        if (pid < 0) {
            std::println(std::cerr, "fork failed for {}", members[i].name);
            ++failed;
            continue;
        }
        if (pid == 0) {
            aura_reset_runtime();
            const int rc = members[i].run();
            std::fflush(nullptr);
            ::_exit(rc == 0 ? 0 : 1);
        }
        int status = 0;
        if (::waitpid(pid, &status, 0) < 0) {
            std::println(std::cerr, "waitpid failed for {}", members[i].name);
            ++failed;
            continue;
        }
        if (WIFEXITED(status) && WEXITSTATUS(status) == 0) {
            ++passed;
        } else {
            ++failed;
            if (WIFSIGNALED(status)) {
                std::println(std::cerr, "bundle member {} crashed signal={}", members[i].name,
                             WTERMSIG(status));
            } else {
                std::println(std::cerr, "bundle member {} failed (rc={})", members[i].name,
                             WIFEXITED(status) ? WEXITSTATUS(status) : -1);
            }
        }
    }

    std::println("──────────────────────────────────────");
    std::println("Total: {} passed, {} failed", passed, failed);
    return failed > 0 ? 1 : 0;
}
