// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"


int main() {
    static const AuraBundleMember members[] = {};
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit", members, n);
}
