// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late1
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_159_bench_run();
extern int aura_issue_677_run();
extern int aura_issue_per_fiber_stack_pool_high_concurrency_run();
extern int aura_issue_aot_bridge_checkpoint_version_steal_run();
extern int aura_issue_macro_hygiene_fiber_panic_aot_soa_self_evo_run();
extern int aura_issue_edsl_core_stability_cow_atomic_query_mutate_run();
extern int aura_issue_compiler_core_incremental_selfmod_gaps_run();
extern int aura_issue_highperf_cpp26_gaps_arena_soa_value_shape_pass_run();
extern int aura_issue_typesystem_typed_mutate_incremental_gaps_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_159_bench", aura_issue_159_bench_run},
        {"test_issue_677", aura_issue_677_run},
        {"test_per_fiber_stack_pool_high_concurrency",
         aura_issue_per_fiber_stack_pool_high_concurrency_run},
        {"test_aot_bridge_checkpoint_version_steal",
         aura_issue_aot_bridge_checkpoint_version_steal_run},
        {"test_macro_hygiene_fiber_panic_aot_soa_self_evo",
         aura_issue_macro_hygiene_fiber_panic_aot_soa_self_evo_run},
        {"test_edsl_core_stability_cow_atomic_query_mutate",
         aura_issue_edsl_core_stability_cow_atomic_query_mutate_run},
        {"test_compiler_core_incremental_selfmod_gaps",
         aura_issue_compiler_core_incremental_selfmod_gaps_run},
        {"test_highperf_cpp26_gaps_arena_soa_value_shape_pass",
         aura_issue_highperf_cpp26_gaps_arena_soa_value_shape_pass_run},
        {"test_typesystem_typed_mutate_incremental_gaps",
         aura_issue_typesystem_typed_mutate_incremental_gaps_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_late1", members, n);
}
