// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_minimal
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_146_run();
extern int aura_issue_147_run();
extern int aura_issue_149_run();
extern int aura_issue_212_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_146", aura_issue_146_run},
        {"test_issue_147", aura_issue_147_run},
        {"test_issue_149", aura_issue_149_run},
        {"test_issue_212", aura_issue_212_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_minimal", members, n);
}
