// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle driver for profile: fiber


#include "test_harness.hpp"

import std;
extern int aura_issue_115_run();
extern int aura_issue_204_run();
extern int aura_issue_205_run();

int main() {
    struct Member {
        const char* name;
        int (*run)();
    };
    Member members[] = {
        {"test_issue_115", aura_issue_115_run},
        {"test_issue_204", aura_issue_204_run},
        {"test_issue_205", aura_issue_205_run},
    };

    int passed = 0;
    int failed = 0;
    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));

    for (int i = 0; i < n_members; ++i) {
        std::fprintf(stdout, "\n════ Bundle member: %s ════\n", members[i].name);
        std::fflush(stdout);
        ::aura::test::g_passed = 0;
        ::aura::test::g_failed = 0;
        const int rc = members[i].run();
        std::fflush(stdout);
        if (rc != 0) {
            std::fprintf(stderr, "bundle member %s failed (rc=%d)\n", members[i].name, rc);
        }
        if (rc == 0) {
            ++passed;
        } else {
            ++failed;
        }
    }

    std::fprintf(stdout, "──────────────────────────────────────\n");
    std::fprintf(stdout, "Total: %d passed, %d failed\n", passed, failed);
    return failed > 0 ? 1 : 0;
}
