// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late2
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_dead_coercion_elision_narrow_evidence_run();
extern int aura_issue_linear_ownership_postmutate_guard_steal_envframe_run();
extern int aura_issue_typechecker_incremental_guard_steal_fidelity_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_dead_coercion_elision_narrow_evidence",
         aura_issue_dead_coercion_elision_narrow_evidence_run},
        {"test_linear_ownership_postmutate_guard_steal_envframe",
         aura_issue_linear_ownership_postmutate_guard_steal_envframe_run},
        {"test_typechecker_incremental_guard_steal_fidelity",
         aura_issue_typechecker_incremental_guard_steal_fidelity_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_late2", members, n);
}
