// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late1
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_159_bench_run();
extern int aura_issue_218_run();
extern int aura_issue_edsl_hygiene_atomic_run();
extern int aura_issue_428_closure_run();
extern int aura_issue_429_soa_run();
extern int aura_issue_430_arena_compaction_run();
extern int aura_issue_431_cxx26_run();
extern int aura_issue_440_edsl_readiness_run();
extern int aura_issue_444_strategy_evolution_run();
extern int aura_issue_445_openclaw_integration_run();
extern int aura_issue_452_aot_hot_update_run();
extern int aura_issue_462_shape_aware_folding_run();
extern int aura_issue_463_soa_phase2_wiring_run();
extern int aura_issue_675_run();
extern int aura_issue_676_run();
extern int aura_issue_677_run();
extern int aura_issue_678_run();
extern int aura_issue_679_run();
extern int aura_issue_680_run();
extern int aura_issue_681_run();
extern int aura_issue_682_run();
extern int aura_issue_683_run();
extern int aura_issue_684_run();
extern int aura_issue_685_run();
extern int aura_issue_686_run();
extern int aura_issue_688_run();
extern int aura_issue_689_run();
extern int aura_issue_690_run();
extern int aura_issue_691_run();
extern int aura_issue_692_run();
extern int aura_issue_694_run();
extern int aura_issue_697_run();
extern int aura_issue_698_run();
extern int aura_issue_706_run();
extern int aura_issue_707_run();
extern int aura_issue_per_fiber_stack_pool_high_concurrency_run();
extern int aura_issue_708_run();
extern int aura_issue_aot_bridge_checkpoint_version_steal_run();
extern int aura_issue_macro_hygiene_fiber_panic_aot_soa_self_evo_run();
extern int aura_issue_edsl_core_stability_cow_atomic_query_mutate_run();
extern int aura_issue_compiler_core_incremental_selfmod_gaps_run();
extern int aura_issue_highperf_cpp26_gaps_arena_soa_value_shape_pass_run();
extern int aura_issue_typesystem_typed_mutate_incremental_gaps_run();
extern int aura_issue_709_run();
extern int aura_issue_710_run();
extern int aura_issue_711_run();
extern int aura_issue_712_run();
extern int aura_issue_713_run();
extern int aura_issue_714_run();
extern int aura_issue_715_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_159_bench", aura_issue_159_bench_run},
        {"test_issue_218", aura_issue_218_run},
        {"test_issue_edsl_hygiene_atomic", aura_issue_edsl_hygiene_atomic_run},
        {"test_issue_428_closure", aura_issue_428_closure_run},
        {"test_issue_429_soa", aura_issue_429_soa_run},
        {"test_issue_430_arena_compaction", aura_issue_430_arena_compaction_run},
        {"test_issue_431_cxx26", aura_issue_431_cxx26_run},
        {"test_issue_440_edsl_readiness", aura_issue_440_edsl_readiness_run},
        {"test_issue_444_strategy_evolution", aura_issue_444_strategy_evolution_run},
        {"test_issue_445_openclaw_integration", aura_issue_445_openclaw_integration_run},
        {"test_issue_452_aot_hot_update", aura_issue_452_aot_hot_update_run},
        {"test_issue_462_shape_aware_folding", aura_issue_462_shape_aware_folding_run},
        {"test_issue_463_soa_phase2_wiring", aura_issue_463_soa_phase2_wiring_run},
        {"test_issue_675", aura_issue_675_run},
        {"test_issue_676", aura_issue_676_run},
        {"test_issue_677", aura_issue_677_run},
        {"test_issue_678", aura_issue_678_run},
        {"test_issue_679", aura_issue_679_run},
        {"test_issue_680", aura_issue_680_run},
        {"test_issue_681", aura_issue_681_run},
        {"test_issue_682", aura_issue_682_run},
        {"test_issue_683", aura_issue_683_run},
        {"test_issue_684", aura_issue_684_run},
        {"test_issue_685", aura_issue_685_run},
        {"test_issue_686", aura_issue_686_run},
        {"test_issue_688", aura_issue_688_run},
        {"test_issue_689", aura_issue_689_run},
        {"test_issue_690", aura_issue_690_run},
        {"test_issue_691", aura_issue_691_run},
        {"test_issue_692", aura_issue_692_run},
        {"test_issue_706", aura_issue_706_run},
        {"test_issue_707", aura_issue_707_run},
        {"test_per_fiber_stack_pool_high_concurrency",
         aura_issue_per_fiber_stack_pool_high_concurrency_run},
        {"test_issue_708", aura_issue_708_run},
        {"test_aot_bridge_checkpoint_version_steal",
         aura_issue_aot_bridge_checkpoint_version_steal_run},
        {"test_macro_hygiene_fiber_panic_aot_soa_self_evo",
         aura_issue_macro_hygiene_fiber_panic_aot_soa_self_evo_run},
        {"test_edsl_core_stability_cow_atomic_query_mutate",
         aura_issue_edsl_core_stability_cow_atomic_query_mutate_run},
        {"test_compiler_core_incremental_selfmod_gaps",
         aura_issue_compiler_core_incremental_selfmod_gaps_run},
        {"test_highperf_cpp26_gaps_arena_soa_value_shape_pass",
         aura_issue_highperf_cpp26_gaps_arena_soa_value_shape_pass_run},
        {"test_typesystem_typed_mutate_incremental_gaps",
         aura_issue_typesystem_typed_mutate_incremental_gaps_run},
        {"test_issue_709", aura_issue_709_run},
        {"test_issue_711", aura_issue_711_run},
        {"test_issue_712", aura_issue_712_run},
        {"test_issue_713", aura_issue_713_run},
        {"test_issue_714", aura_issue_714_run},
        {"test_issue_715", aura_issue_715_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_late1", members, n);
}
