// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle driver for profile: fiber

#include <cstdio>

#include "test_harness.hpp"

extern int aura_issue_115_run();
extern int aura_issue_204_run();
extern int aura_issue_205_run();

int main() {
    struct Member {
        const char* name;
        int (*run)();
    };
    Member members[] = {
        {"test_issue_115", aura_issue_115_run},
        {"test_issue_204", aura_issue_204_run},
        {"test_issue_205", aura_issue_205_run},
    };

    int passed = 0;
    int failed = 0;
    const int n_members = static_cast<int>(sizeof(members) / sizeof(members[0]));

    for (int i = 0; i < n_members; ++i) {
        std::println("\n════ Bundle member: {} ════", members[i].name);
        ::aura::test::g_passed = 0;
        ::aura::test::g_failed = 0;
        const int rc = members[i].run();
        if (rc != 0) {
            std::println(std::cerr, "bundle member {} failed (rc={})", members[i].name, rc);
        }
        if (rc == 0) {
            ++passed;
        } else {
            ++failed;
        }
    }

    std::println("──────────────────────────────────────");
    std::println("Total: {} passed, {} failed", passed, failed);
    return failed > 0 ? 1 : 0;
}
