// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late5
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_637_run();
extern int aura_issue_640_run();
extern int aura_issue_641_run();
extern int aura_issue_642_run();
extern int aura_issue_643_run();
extern int aura_issue_644_run();
extern int aura_issue_645_run();
extern int aura_issue_646_run();
extern int aura_issue_647_run();
extern int aura_issue_648_run();
extern int aura_issue_649_run();
extern int aura_issue_650_run();
extern int aura_issue_651_run();
extern int aura_issue_589_run();
extern int aura_issue_590_run();
extern int aura_issue_479_run();
extern int aura_issue_464_arena_auto_compaction_run();
extern int aura_issue_465_cxx26_hotpath_run();
extern int aura_issue_470_stable_ref_sv_scale_run();
extern int aura_issue_471_dirty_sv_scale_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_637", aura_issue_637_run},
        {"test_issue_640", aura_issue_640_run},
        {"test_issue_641", aura_issue_641_run},
        {"test_issue_642", aura_issue_642_run},
        {"test_issue_643", aura_issue_643_run},
        {"test_issue_644", aura_issue_644_run},
        {"test_issue_645", aura_issue_645_run},
        {"test_issue_646", aura_issue_646_run},
        {"test_issue_647", aura_issue_647_run},
        {"test_issue_648", aura_issue_648_run},
        {"test_issue_649", aura_issue_649_run},
        {"test_issue_650", aura_issue_650_run},
        {"test_issue_651", aura_issue_651_run},
        {"test_issue_589", aura_issue_589_run},
        {"test_issue_590", aura_issue_590_run},
        {"test_issue_479", aura_issue_479_run},
        {"test_issue_464_arena_auto_compaction", aura_issue_464_arena_auto_compaction_run},
        {"test_issue_465_cxx26_hotpath", aura_issue_465_cxx26_hotpath_run},
        {"test_issue_470_stable_ref_sv_scale", aura_issue_470_stable_ref_sv_scale_run},
        {"test_issue_471_dirty_sv_scale", aura_issue_471_dirty_sv_scale_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_late5", members, n);
}
