// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late3
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_791_run();
extern int aura_issue_792_run();
extern int aura_issue_793_run();
extern int aura_issue_794_run();
extern int aura_issue_795_run();
extern int aura_issue_796_run();
extern int aura_issue_797_run();
extern int aura_issue_806_run();
extern int aura_issue_803_run();
extern int aura_issue_stable_ref_cross_cow_provenance_enforcement_run();
extern int aura_issue_primitives_hotpath_registry_slo_run();
extern int aura_issue_aura_result_error_policy_run();
extern int aura_issue_open_issues_phase1_batch_run();
extern int aura_issue_804_run();
extern int aura_issue_atomic_batch_snapshot_stable_ref_ai_loops_run();
extern int aura_issue_stable_ref_cow_subworkspace_concurrent_ai_run();
extern int aura_issue_prompt6_epoch_atomic_visibility_fiber_steal_run();
extern int aura_issue_prompt6_linear_jit_l2_post_invalidate_arena_gc_run();
extern int aura_issue_prompt2_6_impact_scope_quote_lambda_bridge_env_run();
extern int aura_issue_cpp26_contracts_hotpath_arena_soa_value_shape_pass_run();
extern int aura_issue_arena_auto_compact_fiber_defag_shape_dirty_closedloop_run();
extern int aura_issue_shape_jit_pass_deopt_incremental_closedloop_ai_mutate_run();
extern int aura_issue_typesystem_solve_delta_occurrence_priority_heavy_mutate_run();
extern int aura_issue_typesystem_type_propagation_jit_l2_typed_mutate_run();
extern int aura_issue_linear_ownership_occurrence_predicate_mutate_run();
extern int aura_issue_primitives_capture_contract_run();
extern int aura_issue_list_vector_soa_hotpath_ai_loops_run();
extern int aura_issue_longrunning_infra_primitives_run();
extern int aura_issue_scheduler_llm_bottleneck_adaptive_steal_gc_run();
extern int aura_issue_runtime_concurrent_full_cycle_chaos_run();
extern int aura_issue_485_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_791", aura_issue_791_run},
        {"test_issue_792", aura_issue_792_run},
        {"test_issue_793", aura_issue_793_run},
        {"test_issue_794", aura_issue_794_run},
        {"test_issue_795", aura_issue_795_run},
        {"test_issue_796", aura_issue_796_run},
        {"test_issue_797", aura_issue_797_run},
        {"test_issue_806", aura_issue_806_run},
        {"test_issue_803", aura_issue_803_run},
        {"test_stable_ref_cross_cow_provenance_enforcement",
         aura_issue_stable_ref_cross_cow_provenance_enforcement_run},
        {"test_primitives_hotpath_registry_slo", aura_issue_primitives_hotpath_registry_slo_run},
        {"test_aura_result_error_policy", aura_issue_aura_result_error_policy_run},
        {"test_open_issues_phase1_batch", aura_issue_open_issues_phase1_batch_run},
        {"test_issue_804", aura_issue_804_run},
        {"test_atomic_batch_snapshot_stable_ref_ai_loops",
         aura_issue_atomic_batch_snapshot_stable_ref_ai_loops_run},
        {"test_stable_ref_cow_subworkspace_concurrent_ai",
         aura_issue_stable_ref_cow_subworkspace_concurrent_ai_run},
        {"test_prompt6_epoch_atomic_visibility_fiber_steal",
         aura_issue_prompt6_epoch_atomic_visibility_fiber_steal_run},
        {"test_prompt6_linear_jit_l2_post_invalidate_arena_gc",
         aura_issue_prompt6_linear_jit_l2_post_invalidate_arena_gc_run},
        {"test_prompt2_6_impact_scope_quote_lambda_bridge_env",
         aura_issue_prompt2_6_impact_scope_quote_lambda_bridge_env_run},
        {"test_cpp26_contracts_hotpath_arena_soa_value_shape_pass",
         aura_issue_cpp26_contracts_hotpath_arena_soa_value_shape_pass_run},
        {"test_arena_auto_compact_fiber_defag_shape_dirty_closedloop",
         aura_issue_arena_auto_compact_fiber_defag_shape_dirty_closedloop_run},
        {"test_shape_jit_pass_deopt_incremental_closedloop_ai_mutate",
         aura_issue_shape_jit_pass_deopt_incremental_closedloop_ai_mutate_run},
        {"test_typesystem_solve_delta_occurrence_priority_heavy_mutate",
         aura_issue_typesystem_solve_delta_occurrence_priority_heavy_mutate_run},
        {"test_typesystem_type_propagation_jit_l2_typed_mutate",
         aura_issue_typesystem_type_propagation_jit_l2_typed_mutate_run},
        {"test_linear_ownership_occurrence_predicate_mutate",
         aura_issue_linear_ownership_occurrence_predicate_mutate_run},
        {"test_primitives_capture_contract", aura_issue_primitives_capture_contract_run},
        {"test_list_vector_soa_hotpath_ai_loops", aura_issue_list_vector_soa_hotpath_ai_loops_run},
        {"test_longrunning_infra_primitives", aura_issue_longrunning_infra_primitives_run},
        {"test_scheduler_llm_bottleneck_adaptive_steal_gc",
         aura_issue_scheduler_llm_bottleneck_adaptive_steal_gc_run},
        {"test_runtime_concurrent_full_cycle_chaos",
         aura_issue_runtime_concurrent_full_cycle_chaos_run},
        {"test_issue_485", aura_issue_485_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_late3", members, n);
}
