// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: light
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_117_run();
extern int aura_issue_120_run();
extern int aura_issue_131_run();
extern int aura_issue_error_merr_run();
extern int aura_issue_pilot_harness_run();
extern int aura_issue_161_run();
extern int aura_issue_162_run();
extern int aura_issue_163_run();
extern int aura_issue_167_run();
extern int aura_issue_171_run();
extern int aura_issue_181_run();
extern int aura_issue_182_run();
extern int aura_issue_197_run();
extern int aura_issue_246_run();
extern int aura_issue_243_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_117", aura_issue_117_run},
        {"test_issue_120", aura_issue_120_run},
        {"test_issue_131", aura_issue_131_run},
        {"test_error_merr", aura_issue_error_merr_run},
        {"test_pilot_harness", aura_issue_pilot_harness_run},
        {"test_issue_161", aura_issue_161_run},
        {"test_issue_162", aura_issue_162_run},
        {"test_issue_163", aura_issue_163_run},
        {"test_issue_167", aura_issue_167_run},
        {"test_issue_171", aura_issue_171_run},
        {"test_issue_181", aura_issue_181_run},
        {"test_issue_182", aura_issue_182_run},
        {"test_issue_197", aura_issue_197_run},
        {"test_issue_246", aura_issue_246_run},
        {"test_issue_243", aura_issue_243_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("light", members, n);
}
