// AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
// Bundle member table for profile: jit_late4
// Runner: tests/bundles/issue_bundle_runner.cpp

#include "issue_bundle_runner.hh"

extern int aura_issue_497_run();
extern int aura_issue_500_run();
extern int aura_issue_501_hygiene_run();
extern int aura_issue_502_run();
extern int aura_issue_503_run();
extern int aura_issue_504_run();
extern int aura_issue_505_run();
extern int aura_issue_507_run();
extern int aura_issue_508_observability_run();
extern int aura_issue_511_observability_run();
extern int aura_issue_512_observability_run();
extern int aura_issue_513_observability_run();
extern int aura_issue_515_observability_run();
extern int aura_issue_516_observability_run();
extern int aura_issue_521_observability_run();
extern int aura_issue_522_observability_run();
extern int aura_issue_523_observability_run();
extern int aura_issue_524_observability_run();
extern int aura_issue_525_observability_run();
extern int aura_issue_528_observability_run();
extern int aura_issue_530_observability_run();
extern int aura_issue_532_observability_run();
extern int aura_issue_533_observability_run();
extern int aura_issue_534_observability_run();
extern int aura_issue_535_observability_run();
extern int aura_issue_557_observability_run();
extern int aura_issue_601_run();
extern int aura_issue_603_run();
extern int aura_issue_606_run();
extern int aura_issue_614_run();
extern int aura_issue_615_run();
extern int aura_issue_618_run();
extern int aura_issue_620_run();
extern int aura_issue_621_run();
extern int aura_issue_622_run();
extern int aura_issue_624_run();
extern int aura_issue_625_run();
extern int aura_issue_626_run();
extern int aura_issue_631_run();
extern int aura_issue_632_run();
extern int aura_issue_633_run();

int main() {
    static const AuraBundleMember members[] = {
        {"test_issue_497", aura_issue_497_run},
        {"test_issue_500", aura_issue_500_run},
        {"test_issue_501_hygiene", aura_issue_501_hygiene_run},
        {"test_issue_502", aura_issue_502_run},
        {"test_issue_503", aura_issue_503_run},
        {"test_issue_504", aura_issue_504_run},
        {"test_issue_505", aura_issue_505_run},
        {"test_issue_507", aura_issue_507_run},
        {"test_issue_508_observability", aura_issue_508_observability_run},
        {"test_issue_511_observability", aura_issue_511_observability_run},
        {"test_issue_512_observability", aura_issue_512_observability_run},
        {"test_issue_513_observability", aura_issue_513_observability_run},
        {"test_issue_515_observability", aura_issue_515_observability_run},
        {"test_issue_516_observability", aura_issue_516_observability_run},
        {"test_issue_521_observability", aura_issue_521_observability_run},
        {"test_issue_522_observability", aura_issue_522_observability_run},
        {"test_issue_523_observability", aura_issue_523_observability_run},
        {"test_issue_524_observability", aura_issue_524_observability_run},
        {"test_issue_525_observability", aura_issue_525_observability_run},
        {"test_issue_528_observability", aura_issue_528_observability_run},
        {"test_issue_530_observability", aura_issue_530_observability_run},
        {"test_issue_532_observability", aura_issue_532_observability_run},
        {"test_issue_533_observability", aura_issue_533_observability_run},
        {"test_issue_534_observability", aura_issue_534_observability_run},
        {"test_issue_535_observability", aura_issue_535_observability_run},
        {"test_issue_557_observability", aura_issue_557_observability_run},
        {"test_issue_601", aura_issue_601_run},
        {"test_issue_603", aura_issue_603_run},
        {"test_issue_606", aura_issue_606_run},
        {"test_issue_614", aura_issue_614_run},
        {"test_issue_615", aura_issue_615_run},
        {"test_issue_618", aura_issue_618_run},
        {"test_issue_620", aura_issue_620_run},
        {"test_issue_621", aura_issue_621_run},
        {"test_issue_622", aura_issue_622_run},
        {"test_issue_624", aura_issue_624_run},
        {"test_issue_625", aura_issue_625_run},
        {"test_issue_626", aura_issue_626_run},
        {"test_issue_631", aura_issue_631_run},
        {"test_issue_632", aura_issue_632_run},
        {"test_issue_633", aura_issue_633_run},
    };
    constexpr int n = static_cast<int>(sizeof(members) / sizeof(members[0]));
    return aura_run_issue_bundle("jit_late4", members, n);
}
