# AUTO-GENERATED by scripts/gen_issue_bundles.py — do not edit
# Issue test bundles: one executable per link profile.
# Include from CMakeLists.txt after cmake/AuraTest.cmake.

function(aura_add_issue_bundle PROFILE)
    string(TOUPPER "${PROFILE}" _profile_uc)
    set(_members_var "AURA_ISSUE_BUNDLE_${_profile_uc}_MEMBERS")
    if(NOT DEFINED ${_members_var})
        message(FATAL_ERROR "Unknown issue bundle profile: ${PROFILE}")
    endif()
    set(_target "test_issues_${PROFILE}")
    set(_members ${${_members_var}})

    set(_sources "tests/bundles/test_issues_${PROFILE}_main.cpp")
    foreach(_m IN LISTS _members)
        list(APPEND _sources "tests/${_m}.cpp")
    endforeach()

    add_executable(${_target} ${_sources})
    set_property(TARGET ${_target} PROPERTY CXX_MODULE_STD ON)
    target_include_directories(${_target} PRIVATE src tests)
    aura_test_compile_options(${_target})
    target_link_libraries(${_target} PRIVATE aura_test_objects pthread stdc++ stdc++exp aura-reflect)

    # Per-target define (not per-source) so the same test .cpp can
    # also be built as a standalone aura_add_issue_test binary.
    target_compile_definitions(${_target} PRIVATE AURA_ISSUE_BUNDLE_MEMBER=1)

    if(PROFILE STREQUAL "light")
        aura_issue_test_observability(${_target})
    elseif(PROFILE STREQUAL "jit")
        aura_issue_test_link_llvm_jit(${_target})
    elseif(PROFILE STREQUAL "jit_minimal")
        aura_issue_test_link_llvm_jit_minimal(${_target})
    elseif(PROFILE STREQUAL "jit_contract")
        aura_issue_test_link_llvm_jit_contract(${_target})
    elseif(PROFILE STREQUAL "jit_tests")
        aura_issue_test_link_llvm_jit_tests(${_target})
    elseif(PROFILE STREQUAL "fiber")
        aura_issue_test_link_llvm_fiber_stubs(${_target})
    else()
        message(FATAL_ERROR "aura_add_issue_bundle: unsupported profile ${PROFILE}")
    endif()

    _aura_issue_bundle_apply_extras(${_target} ${PROFILE})

    add_test(NAME ${_target}_verification COMMAND ./${_target})
endfunction()

function(_aura_issue_bundle_apply_extras TARGET PROFILE)
    if(PROFILE STREQUAL "light")
        target_include_directories(${TARGET} PRIVATE src/compiler)
        target_include_directories(${TARGET} PRIVATE tests)
        target_sources(${TARGET} PRIVATE src/compiler/aot_mangle.h)
        target_sources(${TARGET} PRIVATE src/compiler/observability_metrics.h)
        target_sources(${TARGET} PRIVATE src/compiler/observability_snapshot.h)
        target_sources(${TARGET} PRIVATE src/compiler/type_concepts_impl.cpp)
    elseif(PROFILE STREQUAL "jit")
        target_include_directories(${TARGET} PRIVATE tests)
    endif()
endfunction()

set(AURA_ISSUE_BUNDLE_LIGHT_MEMBERS test_issue_116;test_issue_117;test_issue_118;test_issue_119;test_issue_120;test_issue_121;test_issue_265;test_issue_122;test_issue_123;test_issue_124;test_issue_125;test_issue_126;test_issue_127;test_issue_128;test_issue_130;test_issue_131;test_error_merr;test_primitives_init;test_harness_pilot;test_issue_132;test_issue_134;test_issue_136;test_issue_161;test_issue_162;test_issue_163;test_issue_167;test_issue_168;test_issue_171;test_issue_173;test_issue_181;test_issue_182;test_issue_197;test_issue_246;test_issue_243)
set(AURA_ISSUE_BUNDLE_JIT_MEMBERS test_issue_135;test_issue_137;test_issue_158;test_issue_159;test_issue_184;test_issue_165;test_issue_166;test_issue_169;test_issue_138;test_issue_139;test_issue_140;test_issue_141;test_issue_142;test_issue_143;test_issue_145;test_issue_187;test_issue_188;test_issue_189;test_issue_190;test_issue_191;test_issue_192;test_issue_193;test_issue_194;test_issue_196;test_issue_247;test_issue_248;test_issue_249;test_issue_250;test_issue_197_observability;test_issue_227;test_issue_240;test_issue_260;test_issue_261;test_issue_262;test_issue_263;test_issue_276;test_issue_277;test_issue_242;test_issue_244;test_issue_267;test_issue_270;test_issue_271;test_issue_272;test_issue_228;test_issue_289;test_issue_482;test_issue_484_minimal;test_issue_290;test_issue_291;test_issue_292;test_issue_293;test_issue_296;test_issue_294;test_issue_295;test_issue_297;test_issue_298;test_issue_300;test_issue_355;test_issue_356;test_issue_358;test_issue_359;test_issue_361;test_issue_362;test_issue_363;test_issue_364;test_issue_365;test_issue_366;test_issue_367;test_issue_368;test_issue_369;test_issue_370;test_issue_373;test_issue_374)
set(AURA_ISSUE_BUNDLE_JIT_MINIMAL_MEMBERS test_issue_146;test_issue_147;test_issue_148;test_issue_149;test_issue_206;test_issue_174;test_issue_208;test_issue_210;test_issue_211;test_issue_212;test_issue_213;test_issue_177;test_issue_213_panic_fiber;test_issue_264)
set(AURA_ISSUE_BUNDLE_JIT_CONTRACT_MEMBERS test_issue_144;test_issue_252;test_issue_253;test_issue_254;test_issue_255;test_issue_256;test_issue_258;test_issue_259;test_issue_273;test_issue_274;test_issue_275)
set(AURA_ISSUE_BUNDLE_JIT_TESTS_MEMBERS test_issue_224;test_issue_224_closure_bridge;test_issue_225_bridge_invalidation;test_issue_226)
set(AURA_ISSUE_BUNDLE_FIBER_MEMBERS test_issue_115;test_issue_204;test_issue_205)
